### ISSUE TITLE
ConnectionResetError: [WinError 10054] 

### ISSUE THREAD

**Issue by Tamieem** [swar/nba_api#100]
I've used this api for one of my projects and it has been working up until yesterday when I last checked, and it is now throwing that error above. I haven't changed my code so I don't know what possibly could have caused this error. Any help?

Further information:  
Trying to access the commonplayerinfo endpoint

"An existing connection was forcibly closed by the remote host"

**Comment by swar** [comment]
Can you access the endpoints via browser? It seems like you might be banned.

What `nba_api` version are you using?

**Comment by Tamieem** [comment]
I can view it via browser. I was using 1.14, didn't realize there was an update, but after updating to 1.1.5, the problem fixed itself. Thanks!
