### ISSUE TITLE
Add Game Box Score Endpoint

### ISSUE THREAD

**Issue by ekrolewicz6** [swar/nba_api#102]
Would be great to add this endpoints and all 5 Measure Types:
- Traditional
- Advanced
- Four Factors
- Misc
- Scoring

URL: https://stats.nba.com/teams/boxscores-misc/
Endpoint: https://stats.nba.com/stats/teamgamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Four+Factors&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlusMinus=N&Rank=N&Season=2019-20&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&VsConference=&VsDivision=

**Comment by swar** [comment]
Hopefully I can find some time during the week to get to this endpoint. Nice work finding it

**Comment by swar** [comment]
Fixed as of [v1.1.8](https://github.com/swar/nba_api/releases/tag/v1.1.8).

**Comment by ekrolewicz6** [comment]
Thanks @swar
