### ISSUE TITLE
boxscoreplayertrackv2 not working for games on 11/22/19 onward

### ISSUE THREAD

**Issue by Ollstar** [swar/nba_api#104]
I cannot load games from 11/22 onward.

NBA may have changed their API again. 

Is anyone else having this problem?

This doesn't work:
https://stats.nba.com/stats/boxscoreplayertrackv2?GameID=0021900224

**Comment by swar** [comment]
@Ollstar 

I am trying to look into this issue, but I can't seem to find where that endpoint originated. However, that link seems to be working for me so maybe it is back?

Sorry for the late response, I have been super busy with work and the holidays

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
