### ISSUE TITLE
NBA CDN?

### ISSUE THREAD

**Issue by hkung77** [swar/nba_api#108]
Would it be possible to expand the api to access the nba CDN for player mugshots?

**Comment by swar** [comment]
Do you have a link or more information regarding this information? This is something that can happen if someone is willing to put the time into expanding the library.

@hkung77  sorry for the delay. I have been super busy with work and the holidays.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.

**Comment by bramski** [comment]
Did this go anywhere? I'm mostly looking for just documentation on how the NBA CDN works! Seems like a lot of the official apps are using it but I don't know what the setup is.
