### ISSUE TITLE
PlayByPlay vs PlayByPlayV2 and GAME_ID length

### ISSUE THREAD

**Issue by oscarbatori** [swar/nba_api#109]
I notice that submitting requests to the PlayByPlay and PlayByPlayV2 endpoints seems to return a message saying that the GAME_ID must be 10 digits long (specified as a regex mismatch). However, I obtained all GAME_ID values through time and found only 976 games have a GAME_ID that is 10 characters long, which doesn't seem right.

Am I missing something here about how to use the legacy API? I am trying to build a history of PlayByPlay data.

**Comment by oscarbatori** [comment]
@swar any chance you might be able to take a look at this or point me in the right direction? Not expecting you to do any work on this, just let me know if the issue is familiar to you.

**Comment by delt87** [comment]
@oscarbatori I believe all NBA game IDs should be 10 digits long. This may be a case of leading 00s being dropped in your vector of game IDs. Try adding two zeros (00) in front of your existing game id string.

**Comment by oscarbatori** [comment]
@delt87 I actually experimented with that theory by prepending the shorter IDs with 0s to make them ten digits long, and to no avail.

**Comment by swar** [comment]
@oscarbatori I need a code snippet to look into or else I wouldn't know where to start. @delt87 is correct when they say that you need to append 0s prior to the gameID to ensure there are 10 characters.

Also, sorry for the delay I have been busy with work and the holidays.

**Comment by oscarbatori** [comment]
This appears to have worked now that I padded appropriately.
