### ISSUE TITLE
Index static player list by active

### ISSUE THREAD

**Issue by willfreeborn** [swar/nba_api#11]
Is it possible to add a field in the static player list to index players by active/non-active?

**Comment by swar** [comment]
This is a good suggestions. We might want to expand both the static team and player lists to include as much information as possible.

If anyone else has suggestions feel free to add them. Will comment back with any extra data we can add into the static lists.

**Comment by swar** [comment]
This has been added in as of [#66]. However, I want to keep this ticket open so we update it at the beginning of the season and maybe add more fields.
