### ISSUE TITLE
PlaybyPlayV2 Live game data error

### ISSUE THREAD

**Issue by ccwoods00** [swar/nba_api#110]
When I use playbyplayV2 for live games the data sets for play_by_play are empty. I'm not getting any info from nba.com but for games that ended yesterday or earlier, it works. How did you guys fix this issue?

**Comment by Djalobre** [comment]
anything on this? @swar

**Comment by swar** [comment]
@ccwoods00 @Djalobre 

I need code snippets in order to help you guys with these types of questions or else I do not know where to start with these questions.

Sorry for the delay in response, I have been super busy with work and the holidays.

**Comment by swar** [comment]
It looks like the live play by play is pulled by an entirely different URL.

**Comment by Djalobre** [comment]
from nba_api.stats.endpoints import playbyplayv2

score = playbyplayv2.PlayByPlayV2(game_id='0021900407')

score = score.get_data_frames()[0]

print(score)


I've tried this one, do you have any idea which one should be used then? :)

**Comment by swar** [comment]
It's not available in this library unfortunately.

It looks like it's this URL: https://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2019/scores/pbp/0021900407_full_pbp.json

But not entirely sure how it works other than the GameID towards the end.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.

**Comment by FarhanSajid1** [comment]
So there isn't an endpoint for actual live data?

**Comment by rsforbes** [comment]
> So there isn't an endpoint for actual live data?


Here's what you ate looking for... it's under the nba_api.live rather than nba.stats.

https://github.com/swar/nba_api/blob/master/src/nba_api/live/nba/endpoints/playbyplay.py
