### ISSUE TITLE
Cannot get url videos from VideoEvents

### ISSUE THREAD

**Issue by HugoLebredo** [swar/nba_api#113]
im using the endpoint VideoEvents for take som urls of videos and always return empty data.
For example the _gameID_ "**0021900354**" and the _eventnum_ **739** I ve checked it and the video exists.

Exists some problem with this endpoint?

Thanks a lot

**Comment by swar** [comment]
There is no problem with the endpoint, the video urls that get spit out are codes and you need to follow the path to figure out how to configure them.

Here is that one you are referring to: https://stats.nba.com/events/?flag=1&GameID=0021900354&GameEventID=739&Season=2019-20&title=Robinson%2026%27%203PT%20Jump%20Shot%20(34%20PTS)%20(Butler%209%20AST)

The video URL: https://videos.nba.com/nba/pbp/media/2019/12/10/0021900354/739/d461c20b-55a3-abf9-f7cf-5e4ac6a78b1e_1280x720.mp4

The API to get this information when you submit it with the following request:

Request:
```python
from nba_api.stats.endpoints import *

raw_data = videodetails.VideoDetails(team_id='1610612748', player_id='1629130', game_id_nullable='0021900354')
print(raw_data.get_response())
print(raw_data.get_json())
```
Response: 
```json
{
   "gi":"0021900354",
   "ei":739,
   "y":2019,
   "m":"12",
   "d":"10",
   "gc":"2019-12-10/ATLMIA",
   "p":5,
   "dsc":"Robinson 26' 3PT Jump Shot (34 PTS) (Butler 9 AST)",
   "ha":"MIA",
   "va":"ATL",
   "hpb":127,
   "hpa":130,
   "vpb":117,
   "vpa":117,
   "pta":1
}
```

Unfortunately, I cannot help you with exactly how that ID is generated.

**Comment by swar** [comment]
Sorry for the delay in response. I have been super busy with work and the holidays.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.

**Comment by avn3r** [comment]
Have anyone been able to figure out how to extract the ID. 
ID: d461c20b-55a3-abf9-f7cf-5e4ac6a78b1e 

Haven't trouble scraping it also since it's aria-hidden=True I can see the URL but can't scrape it.
