### ISSUE TITLE
Is defensehub endpoint non-functional?

### ISSUE THREAD

**Issue by jackeiel** [swar/nba_api#116]
Trying to pull stats on defensive ratings, DVOA, etc. and the DefenseHub endpoint keeps throwing the error:

`defense = defensehub.DefenseHub()`

JSONDecodeError                           Traceback (most recent call last)
<ipython-input-31-5e3e26a87fec> in <module>
----> 1 defense = defensehub.DefenseHub()

//anaconda3/lib/python3.7/site-packages/nba_api/stats/endpoints/defensehub.py in __init__(self, game_scope_detailed, league_id, player_or_team, player_scope, season, season_type_playoffs, proxy, headers, timeout, get_request)
     38         }
     39         if get_request:
---> 40             self.get_request()
     41 
     42     def get_request(self):

//anaconda3/lib/python3.7/site-packages/nba_api/stats/endpoints/defensehub.py in get_request(self)
     48             timeout=self.timeout,
     49         )
---> 50         self.load_response()
     51 
     52     def load_response(self):

//anaconda3/lib/python3.7/site-packages/nba_api/stats/endpoints/defensehub.py in load_response(self)
     51 
     52     def load_response(self):
---> 53         data_sets = self.nba_response.get_data_sets()
     54         self.data_sets = [Endpoint.DataSet(data=data_set) for data_set_name, data_set in data_sets.items()]
     55         self.defense_hub_stat1 = Endpoint.DataSet(data=data_sets['DefenseHubStat1'])

//anaconda3/lib/python3.7/site-packages/nba_api/stats/library/http.py in get_data_sets(self)
     77 
     78     def get_data_sets(self):
---> 79         raw_dict = self.get_dict()
     80         if 'resultSets' in raw_dict:
     81             results = raw_dict['resultSets']

//anaconda3/lib/python3.7/site-packages/nba_api/library/http.py in get_dict(self)
     38 
     39     def get_dict(self):
---> 40         return json.loads(self._response)
     41 
     42     def get_json(self):

//anaconda3/lib/python3.7/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
    346             parse_int is None and parse_float is None and
    347             parse_constant is None and object_pairs_hook is None and not kw):
--> 348         return _default_decoder.decode(s)
    349     if cls is None:
    350         cls = JSONDecoder

//anaconda3/lib/python3.7/json/decoder.py in decode(self, s, _w)
    335 
    336         """
--> 337         obj, end = self.raw_decode(s, idx=_w(s, 0).end())
    338         end = _w(s, end).end()
    339         if end != len(s):

//anaconda3/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Djalobre** [comment]
I'm also trying to figure out if this is functional or not?

I've tried with regular parameters but still getting error.

defense = defensehub.DefenseHub(game_scope_detailed='Season',league_id=r'00',player_or_team='Team',player_scope='All Players',season=2019-20,season_type_playoffs='Regular Season') 

Any idea what could be wrong?

**Comment by swar** [comment]
Some of these endpoints are outdated and therefore not functional. I am not sure what page exposes that endpoint.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.

**Comment by grxthy1** [comment]
Hi there, is there any plan to fix this endpoint? I don't see any other endpoint that supplies this data
