### ISSUE TITLE
Grab score at end of each quarter?

### ISSUE THREAD

**Issue by thezoug** [swar/nba_api#117]
Is there a way to grab the advanced boxscore at the end of each (or a specific) quarter as well overtime periods? The granularity of the data would be super helpful

I'm looking at the docs of 'boxscoreadvancedv2' and it looks like there are some parameters named 'EndPeriod' and 'EndRange' but I'm not sure what the difference is here. I suspect that is the parameter I need, but I haven't been able to get that to work quite yet

[For reference](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/boxscoreadvancedv2.md
)

Does anyone have an example of how to implement this please? Thank you! Awesome project!

**Comment by swar** [comment]
@thezoug 

https://github.com/swar/nba_api/issues/74

I think this will help answer your question.
