### ISSUE TITLE
Playoff Game by Game statistics

### ISSUE THREAD

**Issue by j316chuck** [swar/nba_api#119]
Is there a way to get the statistics of each team's playoff runs as opposed to entire season?  
`playoff_atl_year_stats = TeamYearByYearStats(atlanta_id, season_type_all_star=SeasonTypePlayoffs.playoffs)` seems to return the same result as 
`playoff_atl_year_stats = TeamYearByYearStats(atlanta_id)`

**Comment by j316chuck** [comment]
Also, just wondering how did you figure out what data each endpoint showed?

**Comment by swar** [comment]
There is an analysis tool that I created that helped me analyze the endpoints. It can be found in the tools folder.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
