### ISSUE TITLE
Date constraints for games

### ISSUE THREAD

**Issue by oscarbatori** [swar/nba_api#120]
It seems that the date parameter of the `LeagueGameFinder` endpoint does not work:
```
from nba_api.stats.endpoints import leaguegamefinder
leaguegamefinder.LeagueGameFinder(date_from_nullable='2019-01-01')
```
I also tried with `YYYYMMDD` format, and with a `datetime.datetime` object, but was not able to get this to work. Not a huge deal, the data is small, but maybe just drop the parameter?

Happy to provide a PR if you agree, or alternatively have the correct data format to pass.

**Comment by musabdullah0** [comment]
I was having the same issue. Try the 'MM/DD/YYYY' format.

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
