### ISSUE TITLE
what is GAME_EVENT_ID?

### ISSUE THREAD

**Issue by yniknafs** [swar/nba_api#121]
Any sense for what GAME_EVENT_ID is? 

I want to provide game_id and see if it is a regular season of playoff game. having a hard time finding that.

**Comment by swar** [comment]
Not sure how you would solve this issue because some of these endpoints require a season type parameter where you enter Regular Season or Post Season

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
