### ISSUE TITLE
HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=120)

### ISSUE THREAD

**Issue by drue13** [swar/nba_api#125]
I've got this error before, but I am getting it again today on a code that I run everyday. I tried upgrading the nba api and putting in time.sleep. Neither worked. Any ideas? Thanks!

**Comment by jspiro8** [comment]
I'm having the same issue.  I was getting this error before it was fixed in November with version 1.1.5 and I've been using the same code everyday without any issues since then.

**Comment by drue13** [comment]
I found the solution on the Issue thread before this one.

https://github.com/swar/nba_api/issues/124#issuecomment-577573601

**Comment by swar** [comment]
Fixed as of [v1.1.8](https://github.com/swar/nba_api/releases/tag/v1.1.8).

Please post any additional comments regarding this issue on #124
