### ISSUE TITLE
shotchartdetail.py only provides made shots?

### ISSUE THREAD

**Issue by wallysmithjr** [swar/nba_api#129]
hi, i am using nba_api to look through some statistics. 

however, when i try to pull info from shotchartdetail.py, the output only provides shots that were made (i.e. 'SHOT_MADE_FLAG=1')/ and not all shots that were attempted. 

i was wondering if there was something i could do to have the output also include shots that were attempted, but not made. thank you in advance.

**Comment by swar** [comment]
@wallysmithjr  All good to go here? It's changing the selection type to FGA since FGM is default.
