### ISSUE TITLE
Get Player Championships per Season

### ISSUE THREAD

**Issue by luzer** [swar/nba_api#132]
thanks for all the recent help with timeouts

i dont know a way to get championships for each player (ie, how many championships did Lebron win)
i can get for each team, but that might be fuzy if a player is traded in the middle of the season
any endpoints?

**Comment by swar** [comment]
No endpoints to my knowledge. You're probably better off getting the rosters for the championship games and finding players that way and getting a distinct count on years.

Closing this out, feel free to open if you have another followup.
