### ISSUE TITLE
How to get entire schedule of a season?

### ISSUE THREAD

**Issue by kalpitpant** [swar/nba_api#138]
HI I want to know how to get all the games the happend and that are going to happen in a given season?

Thanks

**Comment by kalpitpant** [comment]
Any update on this? Please.

**Comment by Cellular-** [comment]
Here's a json file that contains the entire 2019-2020 season. You'll have to parse yourself though.
http://data.nba.com/data/10s/v2015/json/mobile_teams/nba/2019/league/00_full_schedule.json

**Comment by kalpitpant** [comment]
Thanks for the reply. This same API I am using right now to get schedule. But do they have something which get schedule from stats.nba.com not from data.nba.com ?

Thanks again!!

**Comment by swar** [comment]
You might have some luck going date by date on this endpoint instead. I can't find anything better. 

https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md

**Comment by swar** [comment]
Actually try out this endpoint and mess around with the seasons, seems much better. https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamgamelogs.md

**Comment by ThiagoPanini** [comment]
Hi everyone! I have the same need of the topic's author and I tried to use `teamgamelogs` endpoint but it seems to have only data from 2016-17 season. You can find below the code I used for extracting the data.

`from nba_api.stats.endpoints import teamgamelogs

team_gamelogs = teamgamelogs.TeamGameLogs()
df = team_gamelogs.team_game_logs.get_data_frame()

print(df['SEASON_YEAR'].value_counts())`

**Comment by karakastarik** [comment]
@ThiagoPanini this not the correct way to fetch the data.

You should try:
`from nba_api.stats.endpoints import TeamGameLogs`
`TeamGameLogs(season_nullable='2021-22').get_data_frames()[0]`

Anyway, this is not working to get schedule (future games).

Is there any update for scheduled data?

**Comment by 4ndeez** [comment]
> Thanks for the reply. This same API I am using right now to get schedule. But do they have something which get schedule from stats.nba.com not from data.nba.com ?
> 
> Thanks again!!

Just in case it still be relevant
https://stats.nba.com/stats/scheduleleaguev2?Season=2024-25&LeagueID=00

Thanks to @kirstywilliams
