### ISSUE TITLE
Getting this error message: ConnectionError: ('Connection aborted.', OSError("(60, 'ETIMEDOUT')",))

### ISSUE THREAD

**Issue by skuan** [swar/nba_api#142]
Just started happening recently.  Tried looking through the issues here but didn't find a solution.  My headers is: 

headers = { 'Host': 'stats.nba.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:61.0) Gecko/20100101 Firefox/61.0', 'Accept': 'application/json, text/plain, /', 'Accept-Language': 'en-US,en;q=0.5', 'Referer': 'https://stats.nba.com/', 'Accept-Encoding': 'gzip, deflate, br', 'Connection': 'keep-alive', }

**Comment by afrederick14** [comment]
Did you find a solution? I just experienced the same problem

**Comment by skuan** [comment]
I did not. I don't know what this is about.

**Comment by swar** [comment]
Your headers are outdated and you should use the most current ones when visiting the page via browser. You should see these two fields in your headers: 

```python
        'x-nba-stats-origin': 'stats',
        'x-nba-stats-token': 'true',
```

**Comment by skuan** [comment]
> Your headers are outdated and you should use the most current ones when visiting the page via browser. You should see these two fields in your headers:
> 
> ```python
>         'x-nba-stats-origin': 'stats',
>         'x-nba-stats-token': 'true',
> ```

Can you provide the full header line? I added the two fields you suggested to my headers and still get the same error message.

**Comment by swar** [comment]
You can find the full headers used for the stats endpoints here:

https://github.com/swar/nba_api/blob/master/nba_api/stats/library/http.py#L8
