### ISSUE TITLE
Headers are out of date again

### ISSUE THREAD

**Issue by nicholas-miles** [swar/nba_api#143]
I'm seeing the following error:
`ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)`

Code I ran:
```
# Get all games
raw_game_data = leaguegamefinder.LeagueGameFinder(league_id_nullable=LeagueIDNullable().nba, season_type_nullable=SeasonType().regular)
```

I followed the instructions in [this issue](https://github.com/swar/nba_api/issues/124), and confirmed that I am on the most recent version.

![image](https://user-images.githubusercontent.com/7267397/76153262-6ed7be80-607e-11ea-8aa0-6f4d8c3a4b37.png)

**Comment by MMuta52** [comment]
Also having this issue again!

**Comment by gidfs** [comment]
I got it working on Postman, but Im unable to replicate it on curl. Anyone having any luck?

**Comment by jtpavlock** [comment]
maybe this will help? https://github.com/jtpavlock/nbapy/commit/26b1a6b96ade2cb554dcd2e63b10e26845e00e33

I had to change the Accept headers

**Comment by swar** [comment]
It seems to be working fine for me. Are you still seeing this issue?

**Comment by swar** [comment]
Reopen if this issue persists.
