### ISSUE TITLE
SynergyPlayTypes() returning empty dataframe

### ISSUE THREAD

**Issue by RCL5** [swar/nba_api#145]
First of all I would like to that you @swar for this amazing work :) 
That being said, I am having a problem when trying to obtaing the playtype stats using the endpoint python module `synergyplaytypes.py`. My code is (very simple) the following:

`from nba_api.stats.endpoints import synergyplaytypes
print(synergyplaytypes.SynergyPlayTypes().get_dict())
print(synergyplaytypes.SynergyPlayTypes().get_data_frames())
`

The first print is giving:
`{'resource': 'synergyplaytype', 'parameters': {'LeagueID': '00', 'SeasonYear': '2019-20', 'SeasonType': 'Regular Season', 'PerMode': 'Totals', 'PlayerOrTeam': 'T', 'PlayType': None, 'TypeGrouping': None}, 'resultSets': [{'name': 'SynergyPlayType', 'headers': ['SEASON_ID', 'TEAM_ID', 'TEAM_ABBREVIATION', 'TEAM_NAME', 'PLAY_TYPE', 'TYPE_GROUPING', 'PERCENTILE', 'GP', 'POSS_PCT', 'PPP', 'FG_PCT', 'FT_POSS_PCT', 'TOV_POSS_PCT', 'SF_POSS_PCT', 'PLUSONE_POSS_PCT', 'SCORE_POSS_PCT', 'EFG_PCT', 'POSS', 'PTS', 'FGM', 'FGA', 'FGMX'], 'rowSet': []}]}`

and thus an empty rowSet (data). Whereas the second print returns: 
`[Empty DataFrame
Columns: [SEASON_ID, TEAM_ID, TEAM_ABBREVIATION, TEAM_NAME, PLAY_TYPE, TYPE_GROUPING, PERCENTILE, GP, POSS_PCT, PPP, FG_PCT, FT_POSS_PCT, TOV_POSS_PCT, SF_POSS_PCT, PLUSONE_POSS_PCT, SCORE_POSS_PCT, EFG_PCT, POSS, PTS, FGM, FGA, FGMX]
Index: []]`

Is this an internal problem or am I doing something wrong?

**Comment by swar** [comment]
```python
from nba_api.stats import endpoints


response = endpoints.SynergyPlayTypes(play_type_nullable='Transition', player_or_team_abbreviation='P', type_grouping_nullable='Offensive')
print(response.get_json())
```

Looks like you need to fill in the parameters for a few of them in order to get them to display data.
