### ISSUE TITLE
Looking for Hollinger's Player Efficiency Rating (PER) Player data. What endpoint is this data in?

### ISSUE THREAD

**Issue by frado3** [swar/nba_api#146]
Hollinger's Player Efficiency Rating (PER). This is player data. I can not find what endpoint it is in. Hopefully someone can help me out here. 

Thanks 

Frado3

**Comment by Hydroptix** [comment]
The NBA's API doesn't provide PER because it is an ESPN statistic, not something that the NBA calculates. You would have to pull PER from a different API
