### ISSUE TITLE
Adding leaguehustlestatsteam endpoint?

### ISSUE THREAD

**Issue by RCL5** [swar/nba_api#147]
Hello, I have been using your program for some time and when trying to get the _hustle team stats_ (https://stats.nba.com/teams/hustle/) or the _box outs team stats_ (https://stats.nba.com/teams/box-outs/) which both share the same `"resource":"leaguehustlestatsteam"` I realized there is no leaguehustlestatsteam endpoint class. Are there any plans for adding it?

Endpoint example: https://stats.nba.com/stats/leaguehustlestatsteam?College=&Conference=&Country=&DateFrom=&DateTo=&Division=&DraftPick=&DraftYear=&GameScope=&GameSegment=&Height=&LastNGames=0&LeagueID=00&Location=&Month=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=PerGame&Period=0&PlayerExperience=&PlayerPosition=&PlusMinus=N&Rank=N&Season=2019-20&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&TeamID=0&VsConference=&VsDivision=&Weight=

**Comment by swar** [comment]
Added in [v1.1.9](https://github.com/swar/nba_api/releases/tag/v1.1.9)
