### ISSUE TITLE
Timeout Errors

### ISSUE THREAD

**Issue by vrnshrm8** [swar/nba_api#149]
I keep getting timeout errors even if I'm putting a timeout = 1 argument

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=1)

I'm trying to pull Advanced BoxScore stats for a player (Karl Malone, ID: 252) for a list of 82 gameID's during his MVP season.

for i in mvp_season:
            df_advanced_boxscore = nba.boxscoreadvancedv2.BoxScoreAdvancedV2(game_id = i, timeout = 1).get_data_frames()[0]

**Comment by afrederick14** [comment]
Hello,

I had a similar issue.  I was working with the CommonPlayerInfo endpoint earlier today without an issue but all of a sudden this problem arose.  I don't seem to be having an issue with other endpoitns.

ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

**Comment by jtpavlock** [comment]
Try executing `time.sleep()` in between calls to the api
