### ISSUE TITLE
How to actually access game-by-game stats?

### ISSUE THREAD

**Issue by martendt** [swar/nba_api#15]
Hi swar, I really appreciate you setting this up! I've been using nba_py for a while, but as it is no longer being supported I'm having issues with it. 

I'm fairly new to python/scraping - I was wondering how to actually access the data - if for example, I wanted to pull all game stats from a certain player, for a certain game. I had trouble finding an explanation in the documentation.

**Comment by swar** [comment]
You can get player gamelogs using [PlayerGameLog endpoint](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playergamelog.md).

Alternatively, you can also use [PlayByPlayV2 endpoint](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playbyplayv2.md) to get PlayByPlay information for the entire game.

**Comment by xeacott** [comment]
Hi @swar is this also the correct endpoint for pulling current game and information? Using the seasonID and current date, I wish to pull all the information about games that are going on for the current date. For example, for today's date (10/19/2018) and season 2018-19, I would like to see when all the games are scheduled, the teams playing, and whos home/away. Then as the games are going on, to update my information to say:

CLE @ TOR        |   WSH @ GSW
Q1 - 7:01 left     |   10:30 pm
17 : 22               |    -blank no score-

Does that make sense?

**Comment by sleggett** [comment]
> Hi @swar is this also the correct endpoint for pulling current game and information? Using the seasonID and current date, I wish to pull all the information about games that are going on for the current date. For example, for today's date (10/19/2018) and season 2018-19, I would like to see when all the games are scheduled, the teams playing, and whos home/away. Then as the games are going on, to update my information to say:
> 
> CLE @ TOR | WSH @ GSW
> Q1 - 7:01 left | 10:30 pm
> 17 : 22 | -blank no score-
> 
> Does that make sense?

In order to achieve this, I had to piece together the info from a couple different Endpoints. I used [scoreboardv2](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md) for all games from a certain date (including today). I used [boxscoresummaryv2](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/boxscoresummaryv2.md) for live score.

**Comment by xeacott** [comment]
Thanks guys - I wanted to mention that I've been using the [scoreboardv2 ](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md)endpoint for both games and live score/game time. I observed the response object during game time last night and I swear [I'm not crazy] but all the information was 3-5 minutes late. Has anyone experienced this behavior?

For example, the Cavs game was over in real time, but when looking at the information the live_period_PT was still indicating there was at least two minutes left in the game with the game score reflecting that too. 

I will keep investigating this and see if this behavior is experienced when using [boxscoresummaryv2 ](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/boxscoresummaryv2.md)
