### ISSUE TITLE
Pulling all game logs for all players in the current season

### ISSUE THREAD

**Issue by asu-35** [swar/nba_api#150]
Hi all,

Hoping someone has been successful at this. I'm trying to pull all game logs for all players in the current season. This is my code. It worked for about 20k rows a week ago, but now I keep getting timed out at about 500 rows. Any ideas? The code in question is the for loop at the end...

```python
from nba_api.stats.endpoints import commonallplayers
# pull all NBA players in current season
common_all_players = commonallplayers.CommonAllPlayers(is_only_current_season=1, league_id='00', season='2019-20')
df_cap = common_all_players.common_all_players.get_data_frame()
df_cap.drop_duplicates().sort_values(by=['PERSON_ID'])
df_cap.to_csv (r'common_all_players.csv', header=True)
players = df_cap['PERSON_ID'].drop_duplicates().values.tolist()

from nba_api.stats.endpoints import playergamelog
# pull all game logs for above players
df_gl = playergamelog.PlayerGameLog(season='2019-20',player_id=players[0]).player_game_log.get_data_frame()

for i in range(len(players)):
    df_gl = df_gl.append(playergamelog.PlayerGameLog(season='2019-20',player_id=players[i]).player_game_log.get_data_frame(), ignore_index=True)
```

**Comment by afrederick14** [comment]
The code looks good. I was running into the same problem when running a pretty extensive loop and getting timed out. The issue was addressed in the thread below but I couldn't find a solution that worked for me. https://github.com/swar/nba_api/issues/150

**Comment by shiggyg** [comment]
Hi @swar , I tried to run a similar code as above and got a timeout error. Is there any solution for this?
