### ISSUE TITLE
Passing stats such as secondary assists, assist points created, potential assist points are not there

### ISSUE THREAD

**Issue by lashballerji7** [swar/nba_api#151]
Passing stats such as secondary assists, assist points created, potential assist points are not there.
From this page of the nba.com stat:
https://stats.nba.com/players/passing/
Is there also someplace where I can find a passing turnover stat?

**Comment by swar** [comment]
That page you linked is using: leaguedashptstats

Unfortunately, if you cannot find a page with the passing turnover stats, I am not sure if you will have any luck.

**Comment by rorono4** [comment]
Is still not possible to get potential assist or potential rebound from nba_api?
