### ISSUE TITLE
Get endpoints from angular

### ISSUE THREAD

**Issue by easis** [swar/nba_api#154]
Hi, I'm developing my own stats NBA library (in C#, private repo atm sorry) and found a way to get (I think) all endpoints directly from the browsers console.

![imagen](https://user-images.githubusercontent.com/50383201/87821234-c594a680-c86f-11ea-96d9-010cb0fcd2ac.png)

Just paste this little code to the developer console (F12 in firefox):

```js
angular.module('nba-ng-hana-services')['_invokeQueue'].forEach((i) => {
	if(!i) return;
	
	let serviceType = i[1];
	if(serviceType !== 'service') return;
	
	let service = i[2];
	let serviceName = (service[0]).replace('Service', '');

	let params = service[1];
	if(params.length != 2) return;
	
	let endpointObj = params[1]();
	
	let endpoints = endpointObj['endpoints'];
	if(endpoints && endpoints.length > 0) {
		endpoints.forEach(subEndpoint => {
			let subEndpointName = subEndpoint['endpoint'];
			console.log('Service: ' + serviceName + ', Endpoint: ' + subEndpointName);
		});
	}
	
	let endpoint = endpointObj['endpoint'];
	
	console.log('Endpoint: ' + serviceName + ', Resource: ' + endpoint);
});
```

I'm not very proficient with js so I'm sure this can be shortened.

Also, you can get some constant definitions:
```js
angular.module('stats')['_invokeQueue'][0][2][1]
```

![imagen](https://user-images.githubusercontent.com/50383201/87821134-9aaa5280-c86f-11ea-8b2d-6307b70a277f.png)

**Comment by rsforbes** [comment]
@easis - I'm unfamiliar with Angular. I installed Node and then Angular. I attempted to run your example, but just get `ReferenceError: angular is not defined`

**Comment by easis** [comment]
@rsforbes Sorry if I've been unclear. This should be executed in browser's console (F12 in firefox):
![imagen](https://user-images.githubusercontent.com/50383201/90315341-13f29f00-df1b-11ea-8de7-3bb304946db8.png)

**Comment by pauldevos** [comment]
> Hi, I'm developing my own stats NBA library (in C#, private repo atm sorry) and found a way to get (I think) all endpoints directly from the browsers console.
> 
> ![imagen](https://user-images.githubusercontent.com/50383201/87821234-c594a680-c86f-11ea-96d9-010cb0fcd2ac.png)
> 
> Just paste this little code to the developer console (F12 in firefox):
> 
> ```js
> angular.module('nba-ng-hana-services')['_invokeQueue'].forEach((i) => {
> 	if(!i) return;
> 	
> 	let serviceType = i[1];
> 	if(serviceType !== 'service') return;
> 	
> 	let service = i[2];
> 	let serviceName = (service[0]).replace('Service', '');
> 
> 	let params = service[1];
> 	if(params.length != 2) return;
> 	
> 	let endpointObj = params[1]();
> 	
> 	let endpoints = endpointObj['endpoints'];
> 	if(endpoints && endpoints.length > 0) {
> 		endpoints.forEach(subEndpoint => {
> 			let subEndpointName = subEndpoint['endpoint'];
> 			console.log('Service: ' + serviceName + ', Endpoint: ' + subEndpointName);
> 		});
> 	}
> 	
> 	let endpoint = endpointObj['endpoint'];
> 	
> 	console.log('Endpoint: ' + serviceName + ', Resource: ' + endpoint);
> });
> ```
> 
> I'm not very proficient with js so I'm sure this can be shortened.
> 
> Also, you can get some constant definitions:
> 
> ```js
> angular.module('stats')['_invokeQueue'][0][2][1]
> ```
> 
> ![imagen](https://user-images.githubusercontent.com/50383201/87821134-9aaa5280-c86f-11ea-8b2d-6307b70a277f.png)

Note: I'm NOT a JavaScript developer. So apologize if the terminology is not on point...

So I added a function that would console.save() after each loop using:

`console.save(angular.module('stats')['_invokeQueue'][0][2][1], "my_object.json");` and this works for some endpoint objects, but not others.

<img width="415" alt="Screen Shot 2020-08-15 at 1 15 16 PM" src="https://user-images.githubusercontent.com/6967308/90318917-67ec8c00-def9-11ea-957f-b7f60fe4a4c0.png">

But even so, all the values are the same -- not the ACTUAL values for EACH endpoint. It's I think for one of the, but not sure which at this point and it's just output with the new name for the "forEach" loop I have, but again, ONLY for those first 10 endpoints...

e.g.

```
 let endpoints = endpointObj['endpoints'];
  if (endpoints && endpoints.length > 0) {
    endpoints.forEach((subEndpoint) => {
      let subEndpointName = subEndpoint['endpoint'];
      console.log('Service: ' + serviceName + ', Endpoint: ' + subEndpointName);
      console.log('------ inner loop: endpointObj:');
      console.log(Object.values(endpointObj));
      console.log(angular.module('stats')['_invokeQueue'][0][2][1]);
      console.log('------ endpointObj end ------ ');
    });
```

I can't seem to access the attributes or keys that would give the equivalent of that 

`angular.module('stats')['_invokeQueue'][0][2][1]` values (a JSON object) for each endpoint. 

The values seem to be hidden in the `[[Scope]`` such as `[['Scope']][2]['Stats']['_invokeQueue'][0][2][1]` or `[['Scope']][2]['obj']` if they were callable in the same manner. 

But while the 'stats' part is accessible, the 'obj' isn't for some reason. 

![Screen Shot 2020-08-15 at 1 13 49 PM](https://user-images.githubusercontent.com/6967308/90318897-383d8400-def9-11ea-8083-c145055176f1.png)

**Comment by easis** [comment]
@pauldevos didn't know `console.save()` existed lol
I'm not a JS developer neither so I can't help in some points. 
`angular.module(string)` expects a module name. Those modules can be found in this file: https://stats.nba.com/scripts/theme.min.js
You can dowload it and beautify or load in the debugger of firefox (and clicking the curly braces button at bottom):
![imagen](https://user-images.githubusercontent.com/50383201/90320482-1a484180-df42-11ea-8f04-616d3eac3ebd.png)
![imagen](https://user-images.githubusercontent.com/50383201/90320487-1e745f00-df42-11ea-98e2-d89c9250ae6e.png)

And then search for `angular.module`:
![imagen](https://user-images.githubusercontent.com/50383201/90320505-38ae3d00-df42-11ea-8789-247799e5fa29.png)

Those modules contains services (constants and endpoints among other resources) accessibles from angular.module(module name)['_invokeQueue']. For example, calling `angular.module('nba-ng-hana-services')['_invokeQueue']` will return an array with 125 items, each item is another array where first element is the string _$provide_, the second is the string _service_ and the third element is another array whose first element is the name of the service (the endpoint name in this case) and the second one are the parameters.

**Comment by swar** [comment]
This looks very nice!

I was able to get all of them into a nice list.


```alltimeleadersgrids
assistleaders
2assisttracker
boxscoreadvancedv2
boxscoredefensive
infographicfanduelplayer
boxscorefourfactorsv2
hustlestatsboxscore
boxscorematchups
boxscoremiscv2
playbyplayv2
boxscoreplayertrackv2
commonplayoffseries
boxscorescoringv2
commonplayoffseries
boxscoretraditionalv2
boxscoreusagev2
winprobabilitypbp
cumestatsplayergames
cumestatsplayer
cumestatsteamgames
cumestatsteam
draftcombinedrillresults
draftcombineplayeranthro
draftcombinenonstationaryshooting
draftcombinespotshooting
drafthistory
draftboard
playercompare
fantasywidget
franchisehistory
gamerotation
homepagev2
defensehub
leagueLeaders
leaguelineupviz
leaguedashlineups
leagueseasonmatchups
leaguedashplayerbiostats
leaguedashplayerclutch
playerestimatedmetrics
leaguedashplayerstats
leaguehustlestatsplayerleaders
leaguehustlestatsplayer
leagueplayerondetails
leaguedashplayershotlocations
leaguedashptdefend
leaguedashplayerptshot
leaguedashteamclutch
teamestimatedmetrics
leaguedashteamstats
leaguehustlestatsteamleaders
leaguehustlestatsteam
leaguedashteamshotlocations
leaguedashoppptshot
leaguedashteamptshot
matchupsrollup
playervsplayer
playerawards
playercareerbycollegerollup
playercareerbycollege
playercareerstats
playerfantasyprofilebargraph
playerfantasyprofile
playergamelog
playerprofilev2
commonallplayers
playerdashboardbyshootingsplits
playerdashboardbygeneralsplits
playerdashboardbyopponent
playerdashboardbylastngames
playerdashboardbygamesplits
playerdashboardbyclutch
playerdashboardbyteamperformance
playerdashboardbyyearoveryear
playerdashboardbygeneralsplits
commonplayerinfo
playerdashptshotdefend
playerdashptpass
playerdashptreb
playerdashptshots
playerdashptreboundlogs
playerdashptshotlog
playernextngames
dleaguepredictor
shotchartleaguewide
glalumboxscoresimilarityscore
boxscoresimilarityscore
playertrackbucketsimilarityscore
playertrackranksimilaritycomp
playertracksimilarityscore
playertracksimilarityuniqueness
synergybucketsimilarityscore
synergysimilarityscore
leaguestandingsv3
synergyplaytypes
franchiseplayers
teamgamelog
teamdashlineups
teamplayeronoffdetails
teamplayeronoffsummary
teamplayerdashboard
teamdetails
franchiseleaders
commonteamroster
teamyearbyyearstats
teamdashboardbyshootingsplits
teamdashboardbygeneralsplits
teamdashboardbyopponent
teamdashboardbylastngames
teamdashboardbygamesplits
teamdashboardbyclutch
teamdashboardbyteamperformance
teamdashboardbyyearoveryear
teamdashboardbygeneralsplits
teaminfocommon
teamdashptpass
teamdashptreb
teamdashptshots
videoStatus
teamandplayersvsplayers```

**Comment by swar** [comment]
Here are some endpoints that I was not able to find with this method (I don't know if they are deprecated or not.)

```
allplayers
--
allstarballotpredictor
assisttracker
assisttrackerstats
boxscoreadvanced
boxscorefourfactors
boxscoremisc
boxscoreplayertracking
boxscorescoring
boxscoresummary
boxscoresummaryv2
boxscoretraditional
boxscoreusage
commonteamyears
draftcombineplayermeasurements
draftcombinestats
gleaguepredictor
homepage
homepageleaders
leaderstiles
leaguedashptstats
leaguedashptteamdefend
leaguegamefinder
leaguegamelog
leaguestandings
lineupstats
playbyplay
playbyplaymini
playerbiostats
playerclutchstats
playercomparestats
playerdefensestats
playergamelogs
playergamelogsstats
playergamesplitsstats
playergamestreakfinder
playergeneralsplitsstats
playerinfo
playerlastngamesstats
playerondetails
playeropponentstats
playerpassesstats
playerprofile
playerreboundsstats
playerscareerstats
playersclutchstats
playersdefensestats
playersgeneralstats
playershotchartdetail
playershotsstats
playershustleleaders
playershustlestats
playersshotlocationstats
playersshotstats
playerstrackingstats
playersvsplayers
playerteamperformancestats
playeryearoveryearstats
playoffpicture
playoffseries
scoreboard
scoreboardmini
scoreboardv2
shotchartdetail
shotchartlineupdetail
teamandplayervsplayers
teamclutchstats
teamfranchiseleaders
teamfranchiseleadersrank
teamgamelogs
teamgamesplitsstats
teamgamestreakfinder
teamgeneralsplitsstats
teamhistoricalleaders
teaminfo
teamlastngamesstats
teamlineupstats
teamopponentstats
teampassesstats
teamperformancestats
teamplayerstats
teamreboundsstats
teamroster
teamsclutchstats
teamsdefensestats
teamsgeneralstats
teamshootingsplitsstats
teamshotchartlineupdetail
teamshotsstats
teamshustleleaders
teamshustlestats
teamsshotlocationstats
teamsshotstats
teamsyearbyyearstats
teamvsplayer
teamyearoveryearstats
teamyears
videodetails
videoevents
winprobabilityplaybyplay
```

**Comment by swar** [comment]
Here are some that I didn't have that I will add to my analyzer:

```
alltimeleadersgrids
2assisttracker
cumestatsplayergames
cumestatsplayer
cumestatsteamgames
cumestatsteam
draftboard
gamerotation
leaguelineupviz
playerestimatedmetrics
leaguehustlestatsplayerleaders
leaguehustlestatsplayer
teamestimatedmetrics
leaguehustlestatsteamleaders
leaguehustlestatsteam
matchupsrollup
playercareerbycollegerollup
playercareerbycollege
dleaguepredictor
shotchartleaguewide
glalumboxscoresimilarityscore
boxscoresimilarityscore
playertrackbucketsimilarityscore
playertrackranksimilaritycomp
playertracksimilarityscore
playertracksimilarityuniqueness
synergybucketsimilarityscore
synergysimilarityscore
leaguestandingsv3
assistleaders
boxscoreadvancedv2
boxscoredefensive
infographicfanduelplayer
boxscorefourfactorsv2
hustlestatsboxscore
boxscorematchups
boxscoremiscv2
playbyplayv2
boxscoreplayertrackv2
commonplayoffseries
boxscorescoringv2
commonplayoffseries
boxscoretraditionalv2
boxscoreusagev2
winprobabilitypbp
draftcombinedrillresults
draftcombineplayeranthro
draftcombinenonstationaryshooting
draftcombinespotshooting
drafthistory
playercompare
fantasywidget
franchisehistory
homepagev2
defensehub
leagueLeaders
leaguedashlineups
leagueseasonmatchups
leaguedashplayerbiostats
leaguedashplayerclutch
leaguedashplayerstats
leagueplayerondetails
leaguedashplayershotlocations
leaguedashptdefend
leaguedashplayerptshot
leaguedashteamclutch
leaguedashteamstats
leaguedashteamshotlocations
leaguedashoppptshot
leaguedashteamptshot
playervsplayer
playerawards
playercareerstats
playerfantasyprofilebargraph
playerfantasyprofile
playergamelog
playerprofilev2
commonallplayers
playerdashboardbyshootingsplits
playerdashboardbygeneralsplits
playerdashboardbyopponent
playerdashboardbylastngames
playerdashboardbygamesplits
playerdashboardbyclutch
playerdashboardbyteamperformance
playerdashboardbyyearoveryear
playerdashboardbygeneralsplits
commonplayerinfo
playerdashptshotdefend
playerdashptpass
playerdashptreb
playerdashptshots
playerdashptreboundlogs
playerdashptshotlog
playernextngames
synergyplaytypes
franchiseplayers
teamgamelog
teamdashlineups
teamplayeronoffdetails
teamplayeronoffsummary
teamplayerdashboard
teamdetails
franchiseleaders
commonteamroster
teamyearbyyearstats
teamdashboardbyshootingsplits
teamdashboardbygeneralsplits
teamdashboardbyopponent
teamdashboardbylastngames
teamdashboardbygamesplits
teamdashboardbyclutch
teamdashboardbyteamperformance
teamdashboardbyyearoveryear
teamdashboardbygeneralsplits
teaminfocommon
teamdashptpass
teamdashptreb
teamdashptshots
videoStatus
teamandplayersvsplayers
```
