### ISSUE TITLE
api end point for schedule? e.g https://stats.nba.com/schedule/#!?Month=11

### ISSUE THREAD

**Issue by RuijieZ** [swar/nba_api#156]
Does this library provide the mapping of the endpoint for the schedule page?

If not, where I can find more info about this particular endpoint? Any help would be greatly appreciated.

**Comment by rsforbes** [comment]
@swar - I was going to take a look at this and run an analysis against the endpoint. I'm struggling to figure out how to go about doing that. Here's what I tried...

`$ python
>>> from analysis import analyze_and_save_all_endpoints                                  
>>> analyze_and_save_all_endpoints('https://stats.nba.com/schedule')`

The results were...
`deprecated h
deprecated t
skipping deprecated t
deprecated p
deprecated s
invalid failed to pass minimal values test
invalid :
deprecated /
skipping deprecated /
skipping deprecated s
skipping deprecated t
deprecated a
skipping deprecated t
skipping deprecated s
deprecated .
deprecated n
deprecated b
skipping deprecated a
skipping deprecated .
deprecated c
deprecated o
deprecated m
skipping deprecated /
skipping deprecated s
skipping deprecated c
skipping deprecated h
deprecated e
deprecated d
deprecated u
deprecated l
skipping deprecated e`

So what might I be doing wrong?

**Comment by swar** [comment]
@rsforbes  Unfortunately, it's a pretty complicated process to get all the endpoints analyzed. I can add this to my task to do for this weekend. It's been a few months since they were all tested thoroughly anyways.

**Comment by rsforbes** [comment]
If you can create some documentation along the way, that would be super helpful. It would also allow others to contribute as endpoints change.

**Comment by swar** [comment]
@rsforbes 

This endpoint is not apart of the stats endpoints and would need customization in order to get it added to the library. This is a larger undertaking to get working so I'm not sure if I will be able to add it in at this time

**Comment by swar** [comment]
Here is an alternative for the schedule page: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md

**Comment by swar** [comment]
Actually try out this endpoint and mess around with the seasons, seems much better. https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamgamelogs.md

**Comment by karakastarik** [comment]
I tried to fetch the data using [teamgamelogs](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamgamelogs.md) and [scoreboardv2](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md) endpoints but it did not work to get future games, any update?
