### ISSUE TITLE
Get team players stats?

### ISSUE THREAD

**Issue by sword134** [swar/nba_api#158]
Hello,
Currently I am pulling the matches and their respective teams stats, however I want to also add each teams player stats along side the teams names?

For example for a match of grizzlies vs Miami heat I want the team stats alongside of each players stats for each of the respective teams.

**Comment by rsforbes** [comment]
@sword134 If this is still open, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
