### ISSUE TITLE
Getting limited by the API

### ISSUE THREAD

**Issue by JasonKramer525** [swar/nba_api#159]
Are the limits per minute, hour, day posted anywhere? I have been working on a script that runs through a loop to get stats for several players, but I am getting limited even with a small wait time between calls. Is there any way around this or something I can do so that I can runt he full loop? Thanks!

**Comment by cryobry** [comment]
You can add a brief time.sleep() following every API calls:

This seems to work well for me without slowing things down too much:
```
nba_cooldown = random.gammavariate(alpha=9, beta=0.4)
time.sleep(nba_cooldown)
```
