### ISSUE TITLE
APIs are not working on AWS ec2 machine

### ISSUE THREAD

**Issue by kalpitpant** [swar/nba_api#163]
Hi Team,
Your APIs are working fine in my local system but **when I am running it on AWS EC2 machine. It is giving me the below error.**
ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

I thought of testing a url which your API hit to check whether that the url is working or not. **But I am not able to get the leaguegamelog data using below url in my EC2 machine**

[https://stats.nba.com/stats/leaguegamelog?Counter=0&DateFrom=&DateTo=&Direction=ASC&LeagueID=20&PlayerOrTeam=T&Season=2019-20&SeasonType=Regular+Season&Sorter=DATE](url)

**Comment by swar** [comment]
https://github.com/swar/nba_api/issues/101
