### ISSUE TITLE
No API Calls Working

### ISSUE THREAD

**Issue by ds-twsh** [swar/nba_api#168]
I am getting the timeout error for calls to any endpoints on /stats endpoints. This happened on the first time I had made this call in months, so its not that I'm getting blocked.. is anyone else having these problems?

**Comment by SuzuharaTouji** [comment]
I couldn't use the playbyplay endpoints also.

**Comment by rsforbes** [comment]
@ds-twsh - Are you making the call from a code collaborator or public cloud? The NBA blocklists public cloud IPs. If you are using local, please let me know.
