### ISSUE TITLE
Teams   Advanced Box Scores   Advanced  

### ISSUE THREAD

**Issue by Balbuenas** [swar/nba_api#169]
Hi , is there a version of this "leaguegamelog.md" for Advanced Stas? e.g. Ofensive Rtg, Def rtg..etc

**Comment by NBatarilo** [comment]
I'm also looking for this now, haven't noticed this based on the listed end points if it exists

**Comment by rsforbes** [comment]
@Balbuenas  If this is still an open question, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
