### ISSUE TITLE
Differing naming conventions for player id

### ISSUE THREAD

**Issue by nickfarrar** [swar/nba_api#17]
Is there a reason why the player id column in commonplayerinfo.common_player_info is labeled as 'PERSON_ID', but in common_headline_stats it is labeled 'PLAYER_ID'? Obviously this is a really small issue and has an easy workaround, but it makes merging dataframes unnecessarily difficult, unless I am missing a reson why this would have to be..

**Comment by xeacott** [comment]
@nickfarrar I just noticed this as well - I'm assuming its an inconsistency between the API's response attributes. At least be glad that anything related to <player, person, etc.>_id return the same values :)

**Comment by swar** [comment]
@nickfarrar, @xeacott  is correct with his assumption.

The NBA API is not consistent by any means and there are some fields such as Player_ID and Season that have various names but lead to the same data. I've tried doing my best to matching the parameters up on Python, but there is no standardization in the data that is outputted.

This could be a potential feature in a new release to create a standardization map that can be easily updated.
