### ISSUE TITLE
Where can i find the Game_ID?

### ISSUE THREAD

**Issue by Stupidproject** [swar/nba_api#170]
I don't know where can i find the Game_ID.
It's on the webiste or should i code to get it.
Please help.
Thank you.

**Comment by marcelven01** [comment]
Hi,

Check the example on the following link, you'll be able to get the Game_ID from the output dataframe.

https://github.com/swar/nba_api/blob/master/docs/examples/Finding%20Games.ipynb

**Comment by Stupidproject** [comment]
Thank you sir.
This is a very good example for me.
I think i should make nba_api clear first.
