### ISSUE TITLE
CumeStatsPlayer no Output

### ISSUE THREAD

**Issue by marcelven01** [swar/nba_api#172]
Hello,

I have am having issues with the following endpoint.
The code below provides the parameters in the correct format, but the output is always an empty dictionary, does anyone know why no data is being pulled?
PS: the CSV in the code provides the output given by nba_api.stats.endpoints import leaguegamefinder

Thank you!

from nba_api.stats.static import players
from nba_api.stats.endpoints import leaguegamefinder
import pandas as pd
from nba_api.stats.endpoints import CumeStatsPlayer
from nba_api.stats.library.parameters import LeagueID

#  csv has output DF from nba_api.stats.endpoints import leaguegamefinder

nuggets_2019 = pd.read_csv('CSVs\\Game Data - 2019\\Nuggets.csv')
Jokic = players.find_players_by_last_name('Jokic')
ids = nuggets_2019['GAME_ID']
season_id = 42019

jokic_id = Jokic[0]['id']

test = CumeStatsPlayer(player_id = jokic_id, game_ids = ids, season=season_id, league_id = LeagueID.nba)

output = test.game_by_game_stats.get_dict()
print(output)

**Comment by rsforbes** [comment]
The following call is valid. Games must be separated by vertical pipes.

`https://stats.nba.com/stats/cumestatsplayer?LeagueID=00&Season=2022-23&SeasonType=Regular Season&PlayerID=1628369&gameIDs=0022200186|0022200176|0022200163|0022200152`

No issue was found.
