### ISSUE TITLE
LeagueDashTeam and Player stats not working

### ISSUE THREAD

**Issue by ghost** [swar/nba_api#173]
does anyone else have this issue, since yesterday the dataframe is empty

**Comment by swar** [comment]
The Season argument is auto-generated where October indicates the start of the new season. So that value is now generating 2020-21 when that season has not started. Hardcore the argument to 2019-20 and it should start working again.

**Comment by Lucas3062** [comment]
Is it the 'season' argument ? because i've tried and it's still empty, could you do an example ? i'm not that good i think yet ^^.
Here is how you're supposed to do it ? leaguedashteamstats.LeagueDashTeamStats(last_n_games=15,per_mode_detailed='PerGame',season_type_all_star=season_type,season=2019)

**Comment by Lucas3062** [comment]
Nevermind, i found how thanks a lot !
