### ISSUE TITLE
Has anyone had success using the ShotChartLineupDetail endpoint?

### ISSUE THREAD

**Issue by sbut1992** [swar/nba_api#178]
Hi how's it going?

I'm having some issues getting any results from the ShotChartLineupDetail endpoint. When passing in the bare minimum (required parameters), I get back an empty dataframe. 

Has anyone had success with this endpoint, and if so, what parameters/formatting of parameters did you use to get this to work?

Thanks and have a great day.

**Comment by rsforbes** [comment]
If this is still an open question, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw). If it is a bug, please file a bug report.
