### ISSUE TITLE
JSONDecodeError when trying to access LeagueLeaders endpoint

### ISSUE THREAD

**Issue by ethanfuerst** [swar/nba_api#179]
I've been running in to a `JSONDecodeError` while trying to access the LeagueLeaders endpoint. My code is below

`log = leagueleaders.LeagueLeaders(league_id='00', per_mode48='PerGame', scope='S', season='2019-20', season_type_all_star='Regular Season', stat_category_abbreviation='Points')`

Has anyone else ran in to this problem?

**Comment by rsforbes** [comment]
Checkout [StatsCategoryAbbreviations](https://github.com/swar/nba_api/blob/74ef7266e7d18c78d3d784098d994c148da18a38/nba_api/stats/library/parameters.py#L777)

`stat_category_abbreviation='PTS'`

```
from nba_api.stats.endpoints.leagueleaders import LeagueLeaders
log = LeagueLeaders(league_id='00', per_mode48='PerGame', scope='S', season='2019-20', season_type_all_star='Regular Season', stat_category_abbreviation='PTS')

print(log.get_normalized_dict())
```
