### ISSUE TITLE
All players data

### ISSUE THREAD

**Issue by rokas224** [swar/nba_api#180]
Hi guys, how to get dataframe with all players statistics?

Thanks in advance.

**Comment by raiavincent** [comment]
# get_players returns a list of dictionaries, each representing a player.
nba_players = players.get_active_players()
print('Number of players fetched: {}'.format(len(nba_players)))
# convert it froma dictionary to a dataframe
nba_players_df = pd.DataFrame.from_dict(nba_players)
nba_players_df

**Comment by raiavincent** [comment]
Trying to do this as well. What I have tried is pulling all of the active players into a list and using a for loop with get_stats, but that doesn't seem to work.

**Comment by adelhamache** [comment]
i think this video will help you
https://www.youtube.com/watch?v=NCyPY-jfb3I
