### ISSUE TITLE
Net Rating Endpoint

### ISSUE THREAD

**Issue by djgray16** [swar/nba_api#181]
I am trying to find net rating for each team, by season. At the moment, I can only find it per game. Can someone please point me how to find this particular stat? I have cycled through endless endpoints and I can't find it, only estimated net rating (as a sidebar, why are these different?)

Thank you!

**Comment by rsforbes** [comment]
@djgray16 If this is still open, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
