### ISSUE TITLE
Heroku PlayerCareerStats Timeout

### ISSUE THREAD

**Issue by MetaFlash** [swar/nba_api#182]
When using the API on Heroku, 
`players.get_players()`
successfully returns a valid list of players.
However, 
`playercareerstats.PlayerCareerStats(player['id'])`
produces the error
`requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)`
I am on the latest version of the nba_api (1.1.9) and my headers are
`{'Host': 'stats.nba.com', 'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0', 'Accept': 'application/json, text/plain, */*', 'Accept-Language': 'en-US,en;q=0.5', 'Accept-Encoding': 'gzip, deflate, br', 'x-nba-stats-origin': 'stats', 'x-nba-stats-token': 'true', 'Connection': 'keep-alive', 'Referer': 'https://stats.nba.com/', 'Pragma': 'no-cache', 'Cache-Control': 'no-cache'}`
When I run the same code on my computer rather than on Heroku, it works fine.

Does anyone know how to fix this?
Thanks!

**Comment by ebruun** [comment]
Getting the same error! Was it working for you before @MetaFlash?

I was digging around online and found some information from this older client. Seems that NBA is blocking requests from cloud server IPs

https://github.com/bttmly/nba

<img width="885" alt="image" src="https://user-images.githubusercontent.com/55360002/102580423-898a9980-40cc-11eb-9ad4-c357d007ad1b.png">
