### ISSUE TITLE
get_players() hanging

### ISSUE THREAD

**Issue by samhld** [swar/nba_api#189]
I'm having trouble with the `get_players()` function.  I realize it's a lot of players but the function is hanging for 30 minutes before I have to kill it and move on.

Reproduce:
```
from nba_api.stats.static import players
players.get_players()[:5]
```

As a sanity check, `get_teams()` works perfectly.

I watched a demo video and this func returned almost instantly so something is clearly wrong but I can't find a way to troubleshoot it.

**Comment by samhld** [comment]
@swar any thoughts on this?  I can't figure out why this is hanging?  

Anyone else experiencing this or know of a way to get more visibility into where it's getting hung up?

**Comment by rsforbes** [comment]
@samhld - I tried your code today locally and had no issues.

```
from nba_api.stats.static import players
players.get_players()[:5]
```

Output
```
[{'id': 76001,
  'full_name': 'Alaa Abdelnaby',
  'first_name': 'Alaa',
  'last_name': 'Abdelnaby',
  'is_active': False},
 {'id': 76002,
  'full_name': 'Zaid Abdul-Aziz',
  'first_name': 'Zaid',
  'last_name': 'Abdul-Aziz',
  'is_active': False},
 {'id': 76003,
  'full_name': 'Kareem Abdul-Jabbar',
  'first_name': 'Kareem',
  'last_name': 'Abdul-Jabbar',
  'is_active': False},
 {'id': 51,
  'full_name': 'Mahmoud Abdul-Rauf',
  'first_name': 'Mahmoud',
  'last_name': 'Abdul-Rauf',
  'is_active': False},
 {'id': 1505,
  'full_name': 'Tariq Abdul-Wahad',
  'first_name': 'Tariq',
  'last_name': 'Abdul-Wahad',
  'is_active': False}]
```

**Comment by samhld** [comment]
Sounds like a me problem then :)
