### ISSUE TITLE
All team ranks returning as value of 1

### ISSUE THREAD

**Issue by samhld** [swar/nba_api#190]
I found this when using the [`teamplayerdashboard` endpoint](https://github.com/swar/nba_api/blob/74ef7266e7d18c78d3d784098d994c148da18a38/docs/nba_api/stats/endpoints/teamplayerdashboard.md).  

Reproduce:
```
bulls_id = teams.find_teams_by_nickname("Bulls")[0]['id']
tpdash = teamplayerdashboard.TeamPlayerDashboard(bulls_id)
tpdash.team_overall.get_json()
```

Returns:
```
{"headers": ["GROUP_SET", "TEAM_ID", "TEAM_NAME", "GROUP_VALUE", "GP", "W", "L", "W_PCT", "MIN", "FGM", "FGA", "FG_PCT", "FG3M", "FG3A", "FG3_PCT", "FTM", "FTA", "FT_PCT", "OREB", "DREB", "REB", "AST", "TOV", "STL", "BLK", "BLKA", "PF", "PFD", "PTS", "PLUS_MINUS", "GP_RANK", "W_RANK", "L_RANK", "W_PCT_RANK", "MIN_RANK", "FGM_RANK", "FGA_RANK", "FG_PCT_RANK", "FG3M_RANK", "FG3A_RANK", "FG3_PCT_RANK", "FTM_RANK", "FTA_RANK", "FT_PCT_RANK", "OREB_RANK", "DREB_RANK", "REB_RANK", "AST_RANK", "TOV_RANK", "STL_RANK", "BLK_RANK", "BLKA_RANK", "PF_RANK", "PFD_RANK", "PTS_RANK", "PLUS_MINUS_RANK"], "data": [["Overall", 1610612741, "Chicago Bulls", "2020-21", 4, 1, 3, 0.25, 192.0, 152, 351, 0.433, 56, 151, 0.371, 93, 116, 0.802, 33, 136, 169, 96, 75.0, 28, 17, 17, 82, 106, 453, -32.0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]]}
```

The above data is for the Bulls and I know the Bulls don't rank 1 in any of those categories.  `get_data_frame()` also returns 1s.

Any ideas?

**Comment by rsforbes** [comment]
@samhld - Rank is valid only within the players_season_totals. It appears to be a parent-child relationship. 

Essentially what you are viewing is a ranking of players within the context of the team.  If you are looking for something like rank within the context of the league, you'll need to use `leaguestandings` or `leaguestandings3`
