### ISSUE TITLE
Enhancement: Play by Play Video Links

### ISSUE THREAD

**Issue by avn3r** [swar/nba_api#194]
Hi, Thanks for the awesome work.

I manage to get all textual meta-data needed for Play by Play thanks to your API. I do however have a big need for getting the videos for each event of the game. Events are now flag as videURL=1 so we already know which events have a video. However, when you click on a video it takes you to another NBA URL that has the video, but the video/mp4 link its hidden from scrapping tools and I can only scrape it manually. The format of both the websites and the video are easy to decipher but getting the wrong UUID.

### Example: Needed Inputs
```
GAME_ID = '0022000103'
EVENT_ID = 4
SEASON: 2020-21
DATE: '2021-01-05'
RESOLUTION: 1280x720
UUID: **MISSING/INCORRECT**
```

### Event Link:
[https://www.nba.com/stats/events/?GameEventID=4&GameID=0022000103&Season=2020-21&flag=1&sct=plot](https://www.nba.com/stats/events/?GameEventID=4&GameID=0022000103&Season=2020-21&flag=1&sct=plot)
Format: `'https://www.nba.com/stats/events/?GameEventID={EVENT_ID}&GameID={GAME_ID}&Season={SEASON}&flag=1&sct=plot'`

### Event Video:
[https://videos.nba.com/nba/pbp/media/2021/01/05/0022000103/4/7579b05c-c96c-d0a4-ede5-4a90b9ee74a6_1280x720.mp4](https://videos.nba.com/nba/pbp/media/2021/01/05/0022000103/4/7579b05c-c96c-d0a4-ede5-4a90b9ee74a6_1280x720.mp4)
Format: `'https://videos.nba.com/nba/pbp/media/{YEAR}/{MONTH}/{DAY}/{GAME_ID}/{EVENT_ID}/{UUID}_{RESOLUTION}.mp4'`

The one thing missing is the UUID, right now I can only scrape the video link manually (but takes forever and not feasible) since context is hidden scrapper tool can locate URL.

### Code:
```
from nba_api.stats.endpoints import videoevents

game_id = '0022000103'
event_id = 4
video_event = videoevents.VideoEvents(game_id, event_id)
video_specs = video_event.nba_response.get_dict()
print(video_specs)
```
### Output:
```
{'resource': 'videoevents', 'parameters': {'GameID': '0022000103', 'GameEventID': 4}, 'resultSets': {'Meta': {'videoUrls': [{'uuid': '4549dfbf-fde2-4dcc-8065-afade5ada267', 'dur': None, 'stt': None, 'stp': None, 'sth': None, 'stw': None, 'mtt': None, 'mtp': None, 'mth': None, 'mtw': None, 'ltt': None, 'ltp': None, 'lth': None, 'ltw': None}]}, 'playlist': [{'gi': '0022000103', 'ei': 4, 'y': 2021, 'm': '01', 'd': '05', 'gc': '2021-01-05/LALMEM', 'p': 1, 'dsc': 'Jump Ball Valanciunas vs. Davis: Tip to James', 'ha': 'MEM', 'va': 'LAL', 'hpb': 0, 'hpa': 0, 'vpb': 0, 'vpa': 0, 'pta': 1}]}}

Output UUID: 4549dfbf-fde2-4dcc-8065-afade5ada267
Video UUID: 7579b05c-c96c-d0a4-ede5-4a90b9ee74a6
```

The event information is correct but the UUID does not match. I also tried several events and all are returning the same UUID but after further inspection, every video has its own unique UUID.

Is there anything I am missing or doing wrong? Any suggestions as to how to get that UUID for the video URL?

Similar Issue #61

**Comment by XavierReid** [comment]
Hi! I don't know if this will help but once I have the GAME_ID and the EVENT_ID I use `url = 'https://stats.nba.com/stats/videoeventsasset?GameEventID={}&GameID={}'.format(
            event_id, self.id)
        r = requests.get(url, headers=headers)
        json = r.json()
        video_urls = json['resultSets']['Meta']['videoUrls']
        playlist = json['resultSets']['playlist']
        highlight_key = self.id + ':' + event_id
        self.highlights[highlight_key] = {
            'video': video_urls[0]['lurl'],
            'desc': playlist[0]['dsc']
        }`
to get a link to the video event and its description.

**Comment by avn3r** [comment]
>  url = 'https://stats.nba.com/stats/videoeventsasset?GameEventID={}&GameID={}'.format(event_id, self.id)
>   r = requests.get(url, headers=headers)
>   json = r.json()
>   video_urls = json['resultSets']['Meta']['videoUrls']
>   playlist = json['resultSets']['playlist']
>   highlight_key = self.id + ':' + event_id
>   self.highlights[highlight_key] = {
>             'video': video_urls[0]['lurl'],
>             'desc': playlist[0]['dsc']
>    }

Hi @XavierReid thanks for helping out. However, I tried the link you provided and the requests hangs (try to leave it running for 5+ minutes and nothing) it never finishes. Can you show the output of your JSON and the video URL you are getting for the game_id = '0022000103' and event_id = 4.

I get the JSON using videoevents method but no mp4 URL and incorrect UIUD.

**Comment by XavierReid** [comment]
Hey @avn3r I forgot to include the headers I use but when I run:
```
import requests
headers = {
    'Host': 'stats.nba.com',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:72.0) Gecko/20100101 Firefox/72.0',
    'Accept': 'application/json, text/plain, */*',
    'Accept-Language': 'en-US,en;q=0.5',
    'Accept-Encoding': 'gzip, deflate, br',
    'x-nba-stats-origin': 'stats',
    'x-nba-stats-token': 'true',
    'Connection': 'keep-alive',
    'Referer': 'https://stats.nba.com/',
    'Pragma': 'no-cache',
    'Cache-Control': 'no-cache'
}
event_id = '4'
game_id = '0022000103'
url = 'https://stats.nba.com/stats/videoeventsasset?GameEventID={}&GameID={}'.format(
            event_id, game_id)
r = requests.get(url, headers=headers)
json = r.json()
video_urls = json['resultSets']['Meta']['videoUrls']
playlist = json['resultSets']['playlist']
video_event = {'video': video_urls[0]['lurl'], 'desc': playlist[0]['dsc']}
print(video_event)
```
The results are:
```
{'video': 'https://videos.nba.com/nba/pbp/media/2021/01/05/0022000103/4/7579b05c-c96c-d0a4-ede5-4a90b9ee74a6_1280x720.mp4', 'desc': 'Jump Ball Valanciunas vs. Davis: Tip to James'}
```

**Comment by avn3r** [comment]
**Thanks!!!**

I messed up the headers! This is exactly what I needed. I'll bypass using the API and just directly call use the request.

Seriously I even created a bot to manually extract it :/. This was of great help!!!

**Comment by bugczw** [comment]
How to get the total video according to game id without event id?
