### ISSUE TITLE
empty list comes when I tried to call find_players_by_full_name

### ISSUE THREAD

**Issue by Sba121** [swar/nba_api#196]
I'm trying to get Patrick Beverly's id with find_players_by_full_name('Patrick Beverly') but what I get is an empty list.

find_players_by_full_name('Patrick Beverly')
[]

Would somebody help if you guys knows why, please?

**Comment by rsforbes** [comment]
Beverly is spelled with an `ey` at the end. Should be Beverley and you'll get your data.

[Player Data](https://github.com/swar/nba_api/blob/7f0c1dacf46c9fc2112b975be77e08666cb5934e/nba_api/stats/library/data.py)
