### ISSUE TITLE
Does the scoreboard not work?

### ISSUE THREAD

**Issue by kittmiller25** [swar/nba_api#199]
Every time I try to use ScoreboardV2 it times out regardless of how high I set the timeout period

**Comment by p-kossa** [comment]
it appears as though most (all?) box score endpoints aren't working, no clue why.

**Comment by kittmiller25** [comment]
I don't think that its an issue with the code, I think its been blocked by the NBA for some reason, I tried to go to the scoreboard call in my browser straight from the NBA website (https://stats.nba.com/stats/scoreboardV2?DayOffset=0&GameDate=01%2F13%2F2021&LeagueID=00) and that timed out as well

**Comment by p-kossa** [comment]
@kittmiller25 a friend of mine found that the endpoint works if you add a specific header:

`Referer: https://www.nba.com/standings`

**Comment by kittmiller25** [comment]
Would you do that like this? (I'm not super familiar with http)
!pip install nba_api
import json
import requests
from datetime import date
from nba_api.stats.endpoints import scoreboardv2
from nba_api.stats.library.parameters import LeagueID
today = date.today

scores = scoreboardv2.ScoreboardV2(league_id=LeagueID.nba,
        day_offset=0,
        game_date=today,
        headers = {'Referer':'https://www.nba.com/standings'})

that was still timing out for me. I have no idea if this would be the right way to do it but I also tried to go directly to the URIs
https://stats.nba.com/stats/scoreboardV2?DayOffset=0&GameDate=01%2F13%2F2021&LeagueID=00&Referer=https%3A%2F%2Fwww.nba.com%2Fstandings
and 
https://stats.nba.com/stats/scoreboardV2?DayOffset=0&GameDate=01%2F13%2F2021&LeagueID=00&Referer=https://www.nba.com/standings
but those times out as well

**Comment by p-kossa** [comment]
haven't tried in Python yet, I tested it with Postman and got a successful response with that header.

**Comment by kittmiller25** [comment]
ok, thanks, let me know if you end up trying/having any success in python. I tried this too but it didn't work either:
import requests
url = "https://stats.nba.com/stats/scoreboardV2?DayOffset=0&GameDate=01%2F13%2F2021&LeagueID=00"
headers = {'Referer':'https://www.nba.com/standings'}
payload = requests.get(url,headers=headers)

**Comment by rsforbes** [comment]
I had no issues in getting this to work today

```
from nba_api.stats.endpoints import scoreboardv2
scoreboard = scoreboardv2.ScoreboardV2().get_normalized_dict()
print(scoreboard)
```

**Comment by rsforbes** [comment]
@kittmiller25 - Did some digging on your code. Couple of items to point out.

- You are missing parentheses at the end of `date.today`. It should be `date.today()`
- You do not need to create a header as that is handled for you in [NBAHTTP](https://github.com/swar/nba_api/blob/7f0c1dacf46c9fc2112b975be77e08666cb5934e/nba_api/library/http.py) and defined in [NBAStatsHTTP](https://github.com/swar/nba_api/blob/7f0c1dacf46c9fc2112b975be77e08666cb5934e/nba_api/stats/library/http.py). In your case, creating a header is overriding all of the other required heads and thus the call is not going through. 

This will work for you
```
import json
import requests
from datetime import date
from nba_api.stats.endpoints import scoreboardv2
from nba_api.stats.library.parameters import LeagueID

today = date.today()
scores = scoreboardv2.ScoreboardV2(league_id=LeagueID.nba,day_offset=0,game_date=today).get_normalized_dict()
print(scores)
```
