### ISSUE TITLE
Suggestion: Add some automated testing like Travis CI, Circle CI, Appveyor

### ISSUE THREAD

**Issue by cclauss** [swar/nba_api#2]
They are all free for Open Source projects like this one.

https://github.com/marketplace/category/continuous-integration

**Comment by swar** [comment]
Another resource to look into: https://www.obeythetestinggoat.com/pages/book.html#toc

**Comment by cclauss** [comment]
There is a important difference between manual testing and CI tools that automate that testing.

**Comment by jaypeedevlin** [comment]
Sure, but if you're new to unit testing (obviously I'm making a presumption), you need to know what before you can effectively use CI ;)

**Comment by cclauss** [comment]
@jaypeedevlin I think that you can start quickly and safely by linting the code by putting a tool like flake8 or PyLint into a CI job.

**Comment by cclauss** [comment]
@swr Do you want to pick one of the three and then I can create a pull request?

**Comment by swar** [comment]
@cclauss Can't say my decision would be the best in this situation. 

If you are comfortable enough to make the decision, then I am fine with that. I'm assuming it won't be too difficult to switch if we ever need to?

Let me know if there's anything you need me to do from my end.
