### ISSUE TITLE
How to identify the data set type in data_sets?

### ISSUE THREAD

**Issue by whichen** [swar/nba_api#20]
test2 = scoreboardv2.ScoreboardV2(game_date='11/21/2018')
data_sets = test2.data_sets
for i in test2.data_sets:
    print(i.get_json( ))

How can I identify the type of every data set in easiest way? For example 'LastMeeting', 'LineScore', 'SeriesStandings' .

**Comment by xeacott** [comment]
Would type(obj) not be easiest inside your loop for i?

**Comment by whichen** [comment]
> Would type(obj) not be easiest inside your loop for i?

Thanks for your reply. All the type of i are the same "Endpoint.DataSet". But in fact, every i has different heard, I want to get special one. Any one can help?

**Comment by swar** [comment]
Can you provide a link to a documentation page. I'm not understanding what you mean by 'LastMeeting', 'LineScore'

**Comment by whichen** [comment]
> Can you provide a link to a documentation page. I'm not understanding what you mean by 'LastMeeting', 'LineScore'

Thanks for your reply.
FYI https://github.com/swar/nba_api/blob/cc43a9471619cf6124413a01da20de5095b428f6/nba_api/stats/endpoints/scoreboardv2.py
There are different types of dataset like:
self.last_meeting = Endpoint.DataSet(data=data_sets['LastMeeting'])
self.line_score = Endpoint.DataSet(data=data_sets['LineScore'])
How can I identify these types in data set?
