### ISSUE TITLE
season_type_all_star - possible to include both Regular Season and Playoffs?

### ISSUE THREAD

**Issue by robbylewis7** [swar/nba_api#204]
Is it possible to include something like `season_type_all_star=['Playoffs', 'Regular Season']` ?

I ran it but it looks like it only grabs the first value in the array.

**Comment by rsforbes** [comment]
@robbylewis7 - Not exactly sure what you are looking for. `SeasonType` is defined in the `stats.library.parameters` namespace: https://github.com/swar/nba_api/blob/master/nba_api/stats/library/parameters.py

```
class SeasonType:
    regular = 'Regular Season'
    preseason = 'Pre Season'

    default = regular


class SeasonTypePlayoffs(SeasonType):
    playoffs = 'Playoffs'


class SeasonTypeNullable(_NotRequired, SeasonTypePlayoffs):
    pass


class SeasonTypeAllStar(SeasonTypePlayoffs):
    all_star = 'All Star'


class SeasonTypeAllStarNullable(_NotRequired, SeasonTypePlayoffs):
    pass
```

**Comment by robbylewis7** [comment]
Thanks for the response. I'm trying to get the ShotChartDetail for a player for all regular season and playoff games in their career. Is that possible?

**Comment by rsforbes** [comment]
@robbylewis7  If this is still an open question, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
