### ISSUE TITLE
Slack invite has expired

### ISSUE THREAD

**Issue by Nate75Sanders** [swar/nba_api#205]
I tried to use the Slack invite on the GitHub project page, but it seems to have expired AFAICT.

Can you renew it?

Thanks,
Nate

**Comment by rsforbes** [comment]
Try this one: Join my Slack workspace! https://join.slack.com/t/nbaapi/shared_invite/zt-cayfrnfo-s9rySAmBXxBloL09S6N0KA

**Comment by Nate75Sanders** [comment]
K -- so, interesting stuff:

I tried this one, again with Google auth, and it said the same thing: expired.

I decided, unlike the previous invite (the one on the project page), to try with just my email address and that worked, so I'm wondering if somehow these links are fine, but this slack doesn't allow logging in with Google's authenticator?

In any case, this is resolved as far as I'm concerned.

Thanks so much.
