### ISSUE TITLE
Rookies have not been added to players

### ISSUE THREAD

**Issue by peterwilliams-hca** [swar/nba_api#208]
It appears that the rookie class is missing from players.get_active_players() and players.get_players().

**Comment by SpeeJ2** [comment]
I tried the code on #195 and I still don't get how we can get the rookie players id so we can get their stats. Having the example number after commonplayerinfo, which I had to replace with CommonAllPlayers to get it to run, causes an error. I got the data table when I had no number in the ( ), but don't know what to do after that to get the rookie players id and then stats. Please help.

**Comment by rsforbes** [comment]
@SpeeJ2 - Thank you for the feedback. It would appear that you are looking for something like "EXPERIENCE" indicating how many years they have been in the league. I've not checked to see if that is in the data we use to populate this table. I'll remove the PR from this and mark this as an enhancement.

**Comment by rsforbes** [comment]
@SpeeJ2 - Old issue. I came across this while reviewing issues for the upcoming release. The endpoint you are likely looking for is PlayerIndex. That endpoint returns the following data:

` 'PlayerIndex': ["PERSON_ID", "PLAYER_LAST_NAME", "PLAYER_FIRST_NAME", "PLAYER_SLUG", "TEAM_ID", "TEAM_SLUG", "IS_DEFUNCT", "TEAM_CITY", "TEAM_NAME", "TEAM_ABBREVIATION", "JERSEY_NUMBER", "POSITION", "HEIGHT", "WEIGHT", "COLLEGE", "COUNTRY", "DRAFT_YEAR", "DRAFT_ROUND", "DRAFT_NUMBER", "ROSTER_STATUS", "PTS", "REB", "AST", "STATS_TIMEFRAME", "FROM_YEAR", "TO_YEAR"]`
