### ISSUE TITLE
Michael Jordan Shot Data

### ISSUE THREAD

**Issue by robbylewis7** [swar/nba_api#210]
Not sure if anyone else ran into this issue, but in my data run I'm getting 470 playoff shots made for Michael Jordan using the shotchartdetail. It's a lot lower than the actual shots made. Is there an issue with Jordan's data?

**Comment by rsforbes** [comment]
@robbylewis7. If this is still open, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw). If it is a bug, please file a bug report and include the code to reproduce. Thanks!
