### ISSUE TITLE
Rookies not available in stats

### ISSUE THREAD

**Issue by sfckoski** [swar/nba_api#216]
Similar to issue #208, rookies stats are not available from nba_api.stats.static players.get_players() and additiionally, the player_id is not found when calling playerdashboardbyopponent, for examlpe. 

Here's code to find LaMelo's PERSON_ID (stand-in for PLAYER_ID)
```
player_list = commonallplayers.CommonAllPlayers(is_only_current_season=0, league_id='00', season=season)
player_list = player_list.get_data_frames()[0]
player_name = 'LaMelo Ball'
player_id = player_list[player_list['DISPLAY_FIRST_LAST']== player_name]['PERSON_ID']
```

LeMelo doesn't show up in players.get_players() (as well as Desmond Bane, James Wiseman, etc.) and no results returned from stats methods when PERSON_ID/PLAYER_ID passed in. 

```players.find_players_by_last_name('Ball')```

**Comment by edlavairee** [comment]
The player data was last updated on Jan, 27 2020.

I will work on this to get current player data.

**Comment by timsehn** [comment]
I also have this problem. Is there a workaround?

**Comment by sravanpannala** [comment]
You write this code to save the latest player database as a dataframe

```
import pandas as pd
from nba_api.stats.endpoints import commonallplayers as player_info
response = player_info.CommonAllPlayers(is_only_current_season = ['0'],	league_id = ['10'],season=['2021']).get_data_frames()[0]
response['PERSON_ID'] = response['PERSON_ID'].astype(int)
response['FROM_YEAR'] = response['FROM_YEAR'].astype(int)
response['TO_YEAR'] = response['TO_YEAR'].astype(int)
response =response.rename(columns={'PERSON_ID':'pID','DISPLAY_FIRST_LAST':'Name','FROM_YEAR':'From','TO_YEAR':'To'})
data = response[['pID','Name','From','To']]
data.head()
data.to_csv ('WNBA_players_database_2021.csv',index=False)
```
I then save this as a .csv file and have my custom code for importing player dictionaries. I need to run this code once per year to update the players. Here is the function to import players:

```
def get_players(league = 'NBA', from_year =2020, to_year =2020):
    PATH = pathlib.Path(__file__)
    DATA_PATH = PATH.joinpath("../data").resolve()
    data = pd.read_csv(DATA_PATH.joinpath("{0}_players_database_2021.csv".format(league)))  
    from_year = from_year
    to_year = to_year
    player_data = data[(data['From']<=from_year) & (data['To']>=to_year)]
    player_data = player_data.reset_index(drop=True)
    player_dict = player_data.to_dict(orient="records")
    return player_dict
```

**Comment by rsforbes** [comment]
This has been fix with the following commit [e1f2c5187b6ab0a6758d8bfe282586291cbb74d9](https://github.com/swar/nba_api/commit/e1f2c5187b6ab0a6758d8bfe282586291cbb74d9#diff-b414ebeae7e726fc38b7b5d1a3daf728330ace96b4252eac1f710add6b01f53b)

**Comment by LeKD6** [comment]
Hate to reopen this, but I find I have this issue with rookies now. Is there an update?

**Comment by rsforbes** [comment]
@LeKD6 - are you pulling players from the static file or from the api? 

If your using the static file, we only update it when there's a release. The static file can easily become outdated within 24h. While a great idea when the library was first created, the ability to keep it current wasn't fully factored in. There are some tools ability wihtin the source code that maintain this file. Perhaps what we need to do is make the ability to update the file a part of the library itself.

lmk on the static vs api call. Thanks!

**Comment by LeKD6** [comment]
@rsforbes Hey Randy, im using the get_active_players call.
