### ISSUE TITLE
question: anyway to determine a playoff game?

### ISSUE THREAD

**Issue by razbensimon** [swar/nba_api#220]
Hello!
Is there a way to determine if a game is  a  playoff game withe the scoreboardv2 API?
if not, what else can i do to understand that from other api.

thanks

**Comment by wompkins** [comment]
If you look at the GAME_ID value if the first three digits will tell you what type of game it is. See below:
001* - Preseason Game
002* - Regular Season Game
003* - All-Star Game (need to confirm this)
004* - Postseason Game

**Comment by makaroni4** [comment]
@wompkins thanks a ton 🙌 

005 – Play-in game 💡

**Comment by TritonEden** [comment]
### Determine the type of game based on the game id

#### XXXYYGGGGG
XXX: Game type identifier
- 001 = Preseason
- 002 = Regular Season
- 003 = All-Star Game (Also includes Rising Stars games)
- 004 = Playoffs
- 005 = Play-In Tournament (introduced in 2020)
- 006 = NBA Cup Final (introduced in 2023)

YY: Season year indicator
- 46 -> 99 = 1946-47 -> 1999-00
- 00 -> 24 = 2000-01 -> 2024-2025

GGGGG: Unique game number
