### ISSUE TITLE
How to use the Tools (and scripts) in the base directory? Relative imports not correct

### ISSUE THREAD

**Issue by pauldevos** [swar/nba_api#221]
The Tools in the base directory of repository cannot be accessed via the `pip install nba_api` and downloading the package (.zip) and trying to run the scripts (e.g. **analysis.py**) within `tools/stats/endpoint_analysis/` doesn't work. In addition trying to run the Python files in the `scripts` (e.g. **analyze_endpoints_and_create_files.py**) directory also have relative import errors. 

They have Module Import errors like so...

```
ModuleNotFoundError: No module named 'tools'
```

Is there a way to use the **endpoints_analysis.py** or **analyze_endpoints_and_create_files.py** files as is?

**Comment by rsforbes** [comment]
@pauldevos - You'll need to clone the GitHub Repo to get those tools. They are not published to PyPi as they are for development only.
