### ISSUE TITLE
Trying to get all-star seasons only

### ISSUE THREAD

**Issue by MatthewShowman** [swar/nba_api#228]
It's not really and issue; it's more my own inexperience.

I have no problem pulling career stats from the PlayerCareerStats endpoint. But I can't seem to figure out how to grab CareerTotalsAllStarSeason, or maybe it's career_totals_all_star_season. I assume this dataset is (in theory) how to get only seasons in whcih a given player was named to the all-star team, but I could be wrong.

In any case, I'm not sure how to get the CareerTotalsAllStarSeason data. Any ideas?

Thank you in advance.

**Comment by yulincheng00** [comment]
here's my code to get the data
Hope it might be helpful for you!
```
careerstat = nba_api.stats.endpoints.playercareerstats.PlayerCareerStats(per_mode36='PerGame',player_id=202728)
career = careerstat.ccareer_totals_all_star_season.get_data_frame()
```
