### ISSUE TITLE
棒哦

### ISSUE THREAD

**Issue by liaoyongming** [swar/nba_api#23]
你太用心了，但是整套代码感觉没有nba_py来的简洁明了

**Comment by swar** [comment]
Hello! I tried putting this in Google translate, and I was not able to make sense out of this. I apologize that I cannot understand.

对不起，我不懂你的语言

**Comment by whichen** [comment]
> Hello! I tried putting this in Google translate, and I was not able to make sense out of this. I apologize that I cannot understand.
> 
> 对不起，我不懂你的语言

He means your code are very good and you should spend a lot of effort on this. But he think it is not as simple as nba_py (another project in github). 
Appreciate your effort.

**Comment by swar** [comment]
Thank you @whichen for helping translate this for me. 

I appreciate your comments @liaoyongming. I do understand that this project is complex and I am open to any suggestions in making it smoother and easier to use for individuals of all experience levels.
