### ISSUE TITLE
[Q] How can I get the injured players in a specific game (gameId) ?

### ISSUE THREAD

**Issue by yalin** [swar/nba_api#233]
Hi,
I have a question;
I am getting today games using **Scoreboard** and I want to get injured players for each game.
I have the gameId for each game but I couldn't find how to get injured players. 
And if injured players' data is available then there are injured types in general such as "**questionable**", "**out**", "**probable**" etc... Are they also available?

**Comment by rsforbes** [comment]
@yalin If this is still an open question, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
