### ISSUE TITLE
How Many Seasons are Available?

### ISSUE THREAD

**Issue by GratePic** [swar/nba_api#238]
How many seasons are available with this api?

**Comment by rsforbes** [comment]
@GratePic - When I was running the PlayByPlay integration tests looking for issues, I think I was back into the 80s or so. It goes way back. There are some simple calls you could make to grab data by year. If you get a hit within a year, I'd assume the entire season data is there.

**Comment by GratePic** [comment]
Oh cool, I'm in the process of implementing right now. Thanks for the quick reply!
