### ISSUE TITLE
How many times can you make a request in a day?

### ISSUE THREAD

**Issue by ColeBlender** [swar/nba_api#239]

**Comment by rsforbes** [comment]
I've not come across any limits. Theoretically, it would be the following:

24h * 60m * 60s * 1000ms = 86,400,000ms in a day. Divide that by 600ms delay per call (NBA throttle) = 144,000 calls in a 24hr period.

You'll have to give it a try and let us know. When I was determining the throttle, I didn't go millisecond by millisecond. 500ms hit the throttle, 600ms didn't. I didn't experiment with values in between. If you want to squeeze more calls in and find the absolute minimum value, please share. :-D

**Comment by perlovga** [comment]
I'm using random delay between requests from 0.5sec to 1sec and never had issues
