### ISSUE TITLE
How can I get player's current team and JERSEY_NUM?

### ISSUE THREAD

**Issue by whichen** [swar/nba_api#24]
I want to get player's current team and his JERSER_NUM. 
I can only find JERSERY_NUM in infographicfanduelplayer, but I also need to provide a game_id to get it.
Is there a easier way?

**Comment by swar** [comment]
https://github.com/swar/nba_api/blob/master/analysis_archive/stats/analysis.json

Ctrl+F will help locate the fields that you need in each endpoint that it exists in.

[`BoxScoreSummaryV2`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/boxscoresummaryv2.md) -> `InactivePlayers` and `Officials` Datasets
[`InfographicFanDuelPlayer`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/infographicfanduelplayer.md) -> `FanDuelPlayer ` Dataset


However, it looks like there is a JERSEY field as well

[`CommonPlayerInfo`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/commonplayerinfo.md) -> `CommonPlayerInfo` Dataset
[`TeamDetails`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamdetails.md) -> `TeamHof` and `TeamRetired` Datasets

And it looks like there is a NUM field as well

[`CommonTeamRoster`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/commonteamroster.md) -> `CommonTeamRoster` Dataset.


I would refer to CommonTeamRoster and then cycle through all the Teams. That'll probably be the quickest approach as opposed to filter through all GameIDs or PlayerIDs.

**Comment by whichen** [comment]
> https://github.com/swar/nba_api/blob/master/analysis_archive/stats/analysis.json
> 
> Ctrl+F will help locate the fields that you need in each endpoint that it exists in.
> 
> [`BoxScoreSummaryV2`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/boxscoresummaryv2.md) -> `InactivePlayers` and `Officials` Datasets
> [`InfographicFanDuelPlayer`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/infographicfanduelplayer.md) -> `FanDuelPlayer ` Dataset
> 
> However, it looks like there is a JERSEY field as well
> 
> [`CommonPlayerInfo`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/commonplayerinfo.md) -> `CommonPlayerInfo` Dataset
> [`TeamDetails`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/teamdetails.md) -> `TeamHof` and `TeamRetired` Datasets
> 
> And it looks like there is a NUM field as well
> 
> [`CommonTeamRoster`](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/commonteamroster.md) -> `CommonTeamRoster` Dataset.
> 
> I would refer to CommonTeamRoster and then cycle through all the Teams. That'll probably be the quickest approach as opposed to filter through all GameIDs or PlayerIDs.

Thank you, Swar.
