### ISSUE TITLE
Question: How do I pull specific columns from a dataset within an endpoint?

### ISSUE THREAD

**Issue by dquick15** [swar/nba_api#244]
I am struggling to pull specific columns from the playercareerstats endpoint to look at. I understand ".iloc[]" can help separate columns, but I am struggling on how to correctly implement it to manipulate this api. Any tips?

**Comment by rsforbes** [comment]
@dquick15 - Can you post your code? There are also some examples that may be of use in the docs section: https://github.com/swar/nba_api/tree/master/docs/examples

**Comment by dquick15** [comment]
@rsforbes 
#import numpy
#import pandas
#import requests
#import matplotlib
import numpy as np
import pandas as pd
import requests as rq
import matplotlib.pyplot as ply

#find players
from nba_api.stats.static import players 
player_dict = players.get_players()

#Getting Player Regular Season Stats
from nba_api.stats.endpoints import playercareerstats

#Columns to pull from career stats

#Call the API endpoint passing in the player's ID & Per Mode
reg_curry = playercareerstats.PlayerCareerStats(player_id='201939', per_mode36='PerGame') #Curry

**Comment by dquick15** [comment]
curry_cols=reg_curry.get_dict()['PLAYER_ID', 'SEASON_ID', 'TEAM_ABBREVIATION', 'FG_PCT', 'FG3_PCT','FTA', 'FT_PCT','TOV', 'PTS']

I have been trying to pull these columns from playercareerstats

**Comment by dquick15** [comment]
disregard I figured it out
