### ISSUE TITLE
Pulling stats from a dataset in an endpoint

### ISSUE THREAD

**Issue by deniz428** [swar/nba_api#245]
I am working on some code but I am unaware on how to pull stats from a specific data set in an endpoint. I want to get data frin the data set shot5_ft_team_dashboard from the endpoint TeamDashboardByShootingSplits. I am sure the soplution is simple but I am relatively inexperienced when it comes to coding and using APIs. Any help would be appreciated

**Comment by rsforbes** [comment]
@deniz428 If this is still open, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
