### ISSUE TITLE
How to get career stats from career_totals_regular_season?

### ISSUE THREAD

**Issue by RevanthGundala** [swar/nba_api#251]
Hello, I am working on a program right now in python and I'm trying to get some basic stats for certain players. I am new to using API's and I think this is the correct module, but I am unsure of how to implement it. I currently have the player ID, I am just not sure how to use it to receive the data I am looking for. Any help would be appreciated.

**Comment by rsforbes** [comment]
@RevanthGundala. If this is still open, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
