### ISSUE TITLE
[Question] Is there an endpoint for NBA transactions?

### ISSUE THREAD

**Issue by perlovga** [swar/nba_api#253]
How can we pull data from this data stream? I can't find the appropriate endpoint
https://www.nba.com/stats/transactions/

**Comment by vidhanio** [comment]
Found this through the network tab:
https://www.nba.com/stats/js/data/playermovement/NBA_Player_Movement.json

**Comment by perlovga** [comment]
lare reply but thanks for the link. I wrote a couple of functions to get this file and store it in my database. I poll it in a regular interval and get the new items which I put in a queue. This way I push them through to my app which pulls them from the database. An API call would save me some time there.

**Comment by perlovga** [comment]
This has been moved to "https://stats.nba.com/js/data/playermovement/NBA_Player_Movement.json" btw
banged my head a little bit with scraping from dynamic websites before I realised

**Comment by rsforbes** [comment]
For those that may be looking for additional transaction data. I released an [API ](https://pypi.org/project/pro-sports-transactions/) earlier this year for [ProSportsTransactions](https://www.prosportstransactions.com/).

**Comment by kmedved** [comment]
Amazing @rsforbes - that's a great API. I'm the creator of the DARKO NBA projection site (www.darko.app), and I may try and integrate some of that soon.
