### ISSUE TITLE
Cannot reticulate data from python to r 

### ISSUE THREAD

**Issue by jp4200** [swar/nba_api#257]
I can't seem to reticulate my data and it keeps showing multiple errors. The error is "Error in py_call_impl(callable, dots$args, dots$keywords) : NameError: name 'py' is not defined" Does anybody know how to fix this? My reticulate was downloaded from the github version and for some reason the data just isn't transferring over and is showing null values.

**Comment by rsforbes** [comment]
@jp4200  If this is still an open question, please post to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw).
