### ISSUE TITLE
How to get team's shot chart detail?

### ISSUE THREAD

**Issue by whichen** [swar/nba_api#26]
shotchartdetail can get player's shot chart detail that include position(LOC_X and LOC_Y). But I want to get the team's shot detail by game id. 
I find shotchartlineupdetail in your API, but don't know how to use. For example:
stats = shotchartlineupdetail.ShotChartLineupDetail(game_id_nullable='0021800422',team_id_nullable=1610612751)
Can't get ShotChartLineupDetail for team, could you help?

**Comment by swar** [comment]
https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/shotchartdetail.md

You would need to use the ShotChartDetail endpoint and supply a `player_id` and a `team_id` of `0` to get all shot chart information for that player for all seasons. Both of these fields are required. 

So you will need to loop it it through all players giving it a team_id of `0` and once you gather all that information, you can filter it by game_id from the data returned.

**Comment by swar** [comment]
I believe this is the only way to get shot chart info.

**Comment by whichen** [comment]
> I believe this is the only way to get shot chart info.

Thank you.
