### ISSUE TITLE
shotchartdetail returns empty dataframe

### ISSUE THREAD

**Issue by Jake3035** [swar/nba_api#261]
I'm not sure why, since this same code used to work, but now it keeps returning an empty dataframe. I've tried with many different players and years, but it still keeps returning empty dataframes.

![Screenshot 2022-09-11 134819](https://user-images.githubusercontent.com/113311751/189548309-da318a59-c144-45ea-872b-d196a3f58ccd.png)
![Screenshot 2022-09-11 113900](https://user-images.githubusercontent.com/113311751/189548314-e1b6bdf9-2afa-4919-b45a-216543d7ee32.png)

**Comment by nysugfx** [comment]
```
response = shotchartdetail.ShotChartDetail(team_id=1610612754, # 
player_id=player_id, 
context_measure_simple='FGA', 
season_nullable='2021-22', # this should be a string. You have it as an int (2021-22 = 1999)
season_type_all_star='Regular Season')
```

**Comment by Jake3035** [comment]
ohh thanks that worked
