### ISSUE TITLE
Not Getting Response

### ISSUE THREAD

**Issue by palkesh-imenso** [swar/nba_api#262]
Not getting data from any endpoint. I am testing it using postman.

Please help, if anyone has any idea about that.
After getting successful data, I am going to use those end points in my frontend.

**Comment by rsforbes** [comment]
@palkesh-imenso - please post routes you are using, headers, etc. Thanks!

**Comment by rsforbes** [comment]
@palkesh-imenso - I see you posted this in [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw). We can continue the conversation there.
