### ISSUE TITLE
API still works ?

### ISSUE THREAD

**Issue by Fragadule** [swar/nba_api#27]
I can't run the 2 examples scripts.

And a simple test code as this doesn't work for me :(
```
url = 'https://stats.nba.com/stats/boxscoreadvancedv2?EndPeriod=1&EndRange=0&GameID=0021800441&RangeType=0&StartPeriod=1&StartRange=0'
response = requests.get(url)
```

Very nice work by the way, I intend to use it to predict next game individual performances for each player !

**Comment by rajbeard** [comment]
It works for me. What output are you getting when you run those?

**Comment by swar** [comment]
It works for me as well. What error are you seeing? 

Does it work for you in browser? If so, are you including headers in your requests? If you aren't, which it doesn't look like you are, I would add headers to your requests. I believe that will solve your issue. The package includes headers so you could use that instead of making raw requests.

**Comment by Fragadule** [comment]
There is no error, it just doesn't seem to answer.
Actually, with headers (user-agent and cookie), the raw request now works.

But still no for the package, I can't run the Basics script for example. The code `career = playercareerstats.PlayerCareerStats(player_id='203076')` gets no answer (not an error).

I tried to modify the headers in nba_api/nba_api/library/http.py, adding a cookie parameter but it's probably not the right way to go. It still doesn't work for me.

Could it be linked with the fact I run it from France ?

**Comment by Fragadule** [comment]
Ok great, I've made it work !
Had to modify the headers nba_api/nba_api/library/http.py, adding a cookie parameter and modifying the user-agent parameter.

I haven't used it a lot yet, I've just noticed I don't always get the same DF in position 0 in the code `career.get_data_frames()[0]` in the Basics script. Sometimes it's the SeasonTotalsRegularSeason DF like you, but sometimes it's the SeasonRankingsRegularSeason DF

**Comment by swar** [comment]
Would you be able to list what headers you used here? This might help people in the future who are international and are having troubles with their headers.

**Comment by swar** [comment]
If anyone is reading this and still having issues, feel free to create a new issue.
