### ISSUE TITLE
Update static players endpoint with 2022 rookie class

### ISSUE THREAD

**Issue by scottgoodell** [swar/nba_api#270]
It doesn't seem like 2022 rookie class is part of the static players module. Is it possible to update the static players module with the new rookie class in prep for the new season?

Code run:
```
>>> import nba_api.stats.static.players as players
>>> players.find_player_by_id(1631099)
>>>
```

For context: `1631099` is Keegan Murray

https://www.nba.com/player/1631099/keegan-murray

Thanks for all the work maintaining this awesome resource!

**Comment by rsforbes** [comment]
@scottgoodell - Working on some updates this weekend, I'll see if I can't get a release out the first part of the week.

**Comment by rsforbes** [comment]
@scottgoodell - I've updated the [data.py](https://github.com/swar/nba_api/blob/master/nba_api/stats/library/data.py) file. If you want the copy asap, you can download it directly and replace your local file. 

Assuming no python knowledge

1. ` pip show nba-api` will show you where the nba-api package is installed.
2. Go to that folder and navigate to `/stats/library/`
3. Replace `data.py` with the file above.

```
> pip show nba-api

Name: nba-api
.
.
Location: {path}/lib/site-packages  <---
.
.
```

**Comment by scottgoodell** [comment]
Perfect thank you!
