### ISSUE TITLE
Question: Getting nearest defender ID, distance for every shot

### ISSUE THREAD

**Issue by rishabh28patni** [swar/nba_api#295]
Hi! 

Was wondering if the Shotchartdetail endpoint allowed for getting the nearest defender as well as the distance between the defender and the player shooting for each shot? 

If not, any recommendations for how to get this data?

**Comment by rsforbes** [comment]
@rishabh28patni - Please post all questions to [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw). We have an active community there. Thanks!
