### ISSUE TITLE
lineup data by games

### ISSUE THREAD

**Issue by bormilan** [swar/nba_api#304]
Hello, i just wanted to know, is there any way to get which players played in every game ?
I just want to make a training data for prediction, and the players would be important for it, so a need to find a way to calculate which players played in each game.

If its a new feature, i would be happy to help with, i like this project and it would be nice to contribute to it. :D

Thanks!
Milan

**Comment by rsforbes** [comment]
Hi @bormilan - You can find a lot of help over in [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1gwn1du6v-b1oHTZIXcfEp9E06KdBQNw)

**Comment by bormilan** [comment]
Can you send me a New invitation link ? Bc its no longer active.

Thanks

**Comment by rsforbes** [comment]
https://join.slack.com/t/nbaapi/shared_invite/zt-1ipsuai9j-GjZjuP9S2~Uczuny1t74zA

**Comment by rsforbes** [comment]
@bormilan - I fixed the slack link in the readme doc. Thanks for the heads up!
