### ISSUE TITLE
Alternative to cumestatsplayergames for older seasons?

### ISSUE THREAD

**Issue by YKhanTU** [swar/nba_api#308]
I did the following, and just receive an empty response for data:

```
nba_players = players.find_players_by_full_name('Michael Jordan')

for nba_player in nba_players:
    player_id = nba_player['id']
    
    p_games = cumestatsplayergames.CumeStatsPlayerGames(player_id, league_id='00', season='1997-98', season_type_all_star='Regular Season').cume_stats_player_games.get_dict()

    print(p_games)
```

The following code will print out for me:

`{'headers': ['MATCHUP', 'GAME_ID'], 'data': []}`

Even if I leave out `league_id` and `season_type_all_star` to use defaults, still same results.

Am I doing something wrong or is this just not working properly? Or does it not work for older seasons?

**Comment by YKhanTU** [comment]
Ah I guess it just doesn't work for older seasons. That's unfortunate.

Is there another endpoint to use to get cumulative totals (PTS, AST, BLK, STL, FG, FGA, 3P, 3PA, etc.) for older seasons?

**Comment by rsforbes** [comment]
@YKhanTU - I took a look at this call. It appears it was introduced by the NBA during the 2017-2018 season. I'd suggest checking in on [Slack](https://join.slack.com/t/nbaapi/shared_invite/zt-1ipsuai9j-GjZjuP9S2~Uczuny1t74zA) and seeing if others have an answer to your question. You can also search through GitHub repo pretty easy.
