### ISSUE TITLE
Tips for finding endpoints

### ISSUE THREAD

**Issue by msimoni18** [swar/nba_api#312]
First off, great API!

What tips can you provide for finding the endpoints available on [stats.nba.com](url)? For example, if I get player stats using ``playergamelog.PlayerGameLog``, how can I match that data to a page on `stats.nba.com` (if it's even possible)?

I've tried going to different pages and looking at the Network tab in Developer Tools, but haven't been able to find any ``json`` file that is even close to what this endpoint provides.

I'd love to be able to contribute and investigate a possible extension to the NFL or NHL, but I'm having a hard time find how the data is actually being requested.

This would also be helpful because I'm trying to find an endpoint that contains players on each team that includes their season stats.

**Comment by YKhanTU** [comment]
If you go to the `docs` for the endpoints, you'll see for each endpoint the actual stats.nba.com endpoints found that are provided by the developers that you can look at. If I'm not mistaken they even have an example of how they find endpoints in `docs`.
