### ISSUE TITLE
[Bug]: boxscoredefense endpoint failing  

### ISSUE THREAD

**Issue by plourr03** [swar/nba_api#321]
### NBA API Version

1.1.14

### Issue

I am trying to use the boxscoredefensive endpoint and i get the error "KeyError: 'Table1'".

### Code

`boxscoredefensive.BoxScoreDefensive(game_id ='0021900671')`

**Comment by TK05** [comment]
Looks like the `boxscoredefensive` endpoint is dead in favor of `boxscoredefensivev2`.

**Comment by plourr03** [comment]
Im not seeing boxscoredefensivev2. Is that in the endpoints library? 

With the code 
`from nba_api.stats.endpoints.boxscoredefensivev2 import BoxScoreDefensiveV2`

i get the error: ModuleNotFoundError: No module named 'nba_api.stats.endpoints.boxscoredefensivev2'

**Comment by OnerInce** [comment]
That endpoint seems dead, yes. Could try to use boxscoreadvancedv2 ?

**Comment by E3x3** [comment]
BoxScoreMatchups appears to be dead as well, but there doesn't seem to be a v2 version of it.

**Comment by rsforbes** [comment]
BoxScoreDefenseV2 was added in PR #374. This will be released to PyPI later this week.
