### ISSUE TITLE
Anyone here? Are some of these endpoints no longer usable?

### ISSUE THREAD

**Issue by SJ5117** [swar/nba_api#324]
Hello, I get the feeling that some of the endpoints like boxscoretraditionalv2 are no longer able to be accessed by the public. Is this true?

Also, is there another way to discuss here other than opening an issue?

**Comment by rsforbes** [comment]
@SJ5117 - Best method would be Slack; link on the main page. Will take a look at this and some of the other issues that have been posted.

**Comment by SJ5117** [comment]
@rsforbes thank you

**Comment by rsforbes** [comment]
@SJ5117 - I made the following call today for last night's Boston/Cleveland game via Postman. No issues:

```
https://stats.nba.com/stats/boxscoretraditionalv2?GameID=0022200971&StartPeriod=1&EndPeriod=2&StartRange=0&EndRange=0&RangeType=0

          "rowSet": [
                [
                    "0022200971",
                    1610612738,
                    "BOS",
                    "Boston",
                    1627759,
                    "Jaylen Brown",
                    "Jaylen",
                    "F",
                    "",
                    "45:06",
                    12,
                    26,
                    0.462,

```
