### ISSUE TITLE
Team Overall Pace

### ISSUE THREAD

**Issue by ChaseAustin** [swar/nba_api#33]
I am trying to find the average pace from each team like from this chart https://stats.nba.com/teams/advanced/?sort=W&dir=-1

I saw that there is a pace stat from the boxscoreadvancedv2 endpoint, but there is no documentation on the [GameId parameter](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md#GameID)r that it requires.

**Comment by swar** [comment]
GameID is the ID of a game. There is no set list right now available with all GameIDs.

You can probably grab them by season using https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguegamelog.md this Endpoint.

**Comment by swar** [comment]
If it's found on a stats page, it most likely is an API endpoint that can be accessed. 

In that case, the page linked above directs us to [LeagueDashTeamStats](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguedashteamstats.md). I think that's what you were looking for @mikeduin

**Comment by mikeduin** [comment]
Thanks @swar -- appreciate the response! Where I get hung up when making a request to LeagueDashTeamStats is that it requires a few parameters -- OpponentTeamID, Month, Period, and LastNGames -- that are not nullable and don't appear to be required filters on the regular nba.com stats page. Can't seem to be able to zoom out to the view shown on that page. Will keep fiddling with it though.
