### ISSUE TITLE
Playergamelog using dateto and datefrom

### ISSUE THREAD

**Issue by Cellular-** [swar/nba_api#34]
Using the playergamelog endpoints, I can retrieve all games for a specific player. However, to reduce repetition and resource use, I want to only retrieve a days worth of games for a player at a time.

To do this, I thought I could pass in values for the DateFrom and DateTo parameters to the PlayerGameLog function. See the endpoint link below:

https://stats.nba.com/stats/playergamelog?DateFrom=2018-12-23&DateTo=2018-12-23&LeagueID=&PlayerID=2544&Season=2018-19&SeasonType=Regular+Season

If I pass in Dec 23,2018, 12/23/2018, 2018-12-23 or 12/23/2018 for the DateFrom and DateTo values. I get either an error or all the games for the player. There is no documentation for this parameter so it's unclear how to retrieve a players game for a specific day.

**Comment by swar** [comment]
https://stats.nba.com/stats/playergamelog?DateFrom=12/25/2018&DateTo=12/25/2018&LeagueID=&PlayerID=2544&Season=2018-19&SeasonType=Regular+Season

This seems to be working for me. Depending on the error, you may need to URL encode the slashes to `%2F`.

I was able to find this by looking at the Advanced Filter for a player. 
https://stats.nba.com/player/2544/boxscores-traditional/?Season=2018-19&SeasonType=Regular%20Season&DateFrom=12%2F25%2F2018&DateTo=12%2F25%2F2018

**Comment by Cellular-** [comment]
Using MM/DD/YYYY worked. Didn't need to encode slashes either. Not sure why I was getting error but thanks alot. I think adding the default format, MM/DD/YYYY, in the parameter documentation would be helpful for new users.

**Comment by swar** [comment]
The only issue with this is that all of the parameter and endpoint documentation is auto-generated. In addition, we would need to confirm if all DateTo and DateFrom fields are all in that format. The NBA API looks like it was slowly built overtime with varying designs, so MM/DD/YYYY might not be valid for every single endpoint with the date fields.
