### ISSUE TITLE
[Bug]: Live Boxscore doesn't return response for anything before 2019-2023

### ISSUE THREAD

**Issue by oceanrustic** [swar/nba_api#342]
### NBA API Version

V1.2.0

### Issue

Live Boxscore endpoint works great for any game id from 2019-2023. However, it fails for anything from 2018-2019 season or earlier.

For example, here's one that works for a game that occurred from 2019-2023:
https://cdn.nba.com/static/json/liveData/boxscore/boxscore_0022001073.json

And here's one that failed from 2017-2018 season:
https://cdn.nba.com/live/json/liveData/boxscore/boxscore_0021701224.json

Pretty much every game before 2019-2020 season fails for Boxscore endpoint.

Any ideas if this is a bug or some limitation from nba.com?

Thanks

### Code

box = boxscore.BoxScore(game_id, headers=headers)

**Comment by oceanrustic** [comment]
I heard "live" boxscore endpoint didn't exist prior to 2019. When I tried to use boxscoresummaryV2 and bosscoretraditionalV2 to get the pre-2019-20 same type of data as the live boxscore .... I kept getting timeout errors. I tried time.sleep(3) between API call and also tried proxy parameter in the API call with a rotating ip addresses, but neither worked. It would just time out error. Any suggestions on how to get around the timeout errors? And why do the live endpoints not have timeout issues but the regular non-live boxscore endpoints timeout?

**Comment by rsforbes** [comment]
@oceanrustic - for anything historical, use stats.{endpoint}. Live is just for while the game is taking place (not yet in stats). 

The NBA typically makes anything in "live" available in "stats" within a "reasonable" time after the game (sometimes immediately, sometimes within hours)

**Comment by oceanrustic** [comment]
@rsforbes Thanks so much for explaining.  I tried to switch from live to stats to get the same data I wanted but I run into a time out after same 20-30 game ids. Ideally, I get a season of game ids from LeagueGameFinder end point and then pass them into the stats endpoint to build a dataframe that I can then write out to a CSV file.  But it seems to give me a time out error.  I tried using the correct headers. I've also tried a timer.sleep between each API call.  I've also tried passing in a proxy paramater in the endpoint API call.  But it always seems to give me some time out error.  I know there are people who get around this somehow.  Do you have any suggestions on what I might be doing wrong?  This is the call:
def get_data(game_id):
    # box = boxscore.BoxScore(game_id)
    boxTraditional = boxscoretraditionalv2.BoxScoreTraditionalV2(game_id, headers=headers)
    time.sleep(30)

And then this is the headers I use:
headers  = {
    'Connection': 'keep-alive',
    'Accept': 'application/json, text/plain, */*',
    'x-nba-stats-token': 'true',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.130 Safari/537.36',
    'x-nba-stats-origin': 'stats',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Referer': 'https://stats.nba.com/',
    'Accept-Encoding': 'gzip, deflate, br',
    'Accept-Language': 'en-US,en;q=0.9',
}

Thanks!

**Comment by rsforbes** [comment]
I'll have to take a look. 

Depending on what you're looking for,  you could pull data from the LeagueGameLog by Player to get all player's stats for all games. 

Sample URL from Postman:
https://stats.nba.com/stats/leaguegamelog?DateFrom=&DateTo=&Direction=DESC&LeagueID=00&PlayerOrTeam=P&Season=2022-23&SeasonType=Regular Season&Sorter=DATE

This will give you the entire season. You can also use 'Play In', 'Playoffs', 'All Star', & 'Preseason'.
