### ISSUE TITLE
ShotChartLineupDetail empty response

### ISSUE THREAD

**Issue by trytolose** [swar/nba_api#35]
Hello! Thanks for that API.

I have problem with getting shortcharts for current game, returning empty first dataframe. What i'm doing wrong?

`
from nba_api.stats.endpoints import shotchartlineupdetail     
x = shotchartlineupdetail.ShotChartLineupDetail(game_id_nullable ='0021700798')
x.get_data_frames()[0]
`

**Comment by swar** [comment]
You need to supply a player_id and a team_id. Can't filter it by just games.
