### ISSUE TITLE
[Bug]: BoxscoreMatchups no response 

### ISSUE THREAD

**Issue by ChrizzBln89** [swar/nba_api#357]
### NBA API Version

nba-api 1.2.1

### Issue

Hello,

I tried to download the endpoint BoxScoreMatchups. However, I get no response object back, if I try to use the same code for BoxscoreAdvanced it will work.

Any help is appreciated. Thank you in advance.

### Code
game_id = '0027100618'
from nba_api.stats.endpoints import BoxScoreMatchups
boxscorematchups_obj = BoxScoreMatchups(game_id=game_id)
boxscorematchups_dfs = boxscorematchups_obj.get_data_frames()
boxscorematchups_df = boxscorematchups_dfs[0]

**Comment by E3x3** [comment]
It seems many of the Boxscore endpoints give no response right now, I've personally tested all of them using Postman with the given test URLS- no responses. +1

**Comment by JvH13** [comment]
Has this been fixed?

**Comment by rsforbes** [comment]
BoxscoreMatchupsV3 was added in #374. This will be released to PyPI later this week.
