### ISSUE TITLE
get games before 1987

### ISSUE THREAD

**Issue by Yzaza** [swar/nba_api#359]
### NBA API Version

1.2.1

### Issue

I am using trying to understand this api for a while now  but it seems that i can't get games before 1987
is this something to be expected or am i doing something wrong here 

this the output : 

      TEAM_ABBREVIATION     GAME_ID   GAME_DATE SEASON_ID      MATCHUP
0                   DAL  0029901017  2000-03-28     21999    DAL @ LAC
1                   DEN  0029901013  2000-03-28     21999    DEN @ ATL
2                   MIA  0029901012  2000-03-28     21999  MIA vs. PHX
3                   ORL  0029901011  2000-03-28     21999  ORL vs. BOS
4                   HOU  0029901016  2000-03-28     21999  HOU vs. GSW
...                 ...         ...         ...       ...          ...
29995               PHX  0028700277  1987-12-26     21987  PHX vs. SAC
29996               POR  0028700275  1987-12-26     21987    POR @ CLE
29997               HOU  0028700271  1987-12-26     21987    HOU @ DAL
29998               ATL  0028700270  1987-12-25     21987    ATL @ PHL
29999               PHL  0028700270  1987-12-25     21987  PHL vs. ATL

### Code

from nba_api.stats.endpoints import leaguegamefinder
gamefinder = leaguegamefinder.LeagueGameFinder(date_from_nullable="03/28/1950",date_to_nullable="03/28/2000")
games = gamefinder.get_data_frames()[0]
print(games[['TEAM_ABBREVIATION','GAME_ID','GAME_DATE', 'SEASON_ID','MATCHUP']])

**Comment by usharerose** [comment]
The underlying API `/leaguegamefinder` only supports the games from 1987-01-01 in my experience. If just want to fetch the identifier of games, you can alternatively call `/scoreboardv2` supported API.

Compared to `/leaguegamefinder` which supports all supported leagues' games when no declared parameters, `/scoreboardv2` only supports single league's which default is NBA.
