### ISSUE TITLE
LeagueGameFinder doesn't filter out SummerLeague games

### ISSUE THREAD

**Issue by rsforbes** [swar/nba_api#36]
from nba_api.stats.static import teams
from nba_api.stats.endpoints import leaguegamefinder
from nba_api.stats.library.parameters import *

nba_teams = teams.get_teams()
# Select the dictionary for the Pacers, which contains their team ID
pacers = [team for team in nba_teams if team['abbreviation'] == 'IND'][0]
pacers_id = pacers['id']

# Query for games where the Pacers were playing
# Season.Default & SeasonType.regular
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=pacers_id,
                                               season_nullable=Season.default,
                                               season_type_nullable=SeasonType.regular)

games = gamefinder.get_data_frames()[0]
games.count() # Includes 5 Games beyond regular season
games.head(100) #Includes 5 SummerLeague Games

**Comment by rsforbes** [comment]
@swar - how were you able to get a listing of all of the params for the query? I was going to see if there was a param that was missing perhaps.

**Comment by swar** [comment]
@rsforbes 

All details should be on the documentation page here: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguegamefinder.md

However, it looks like I don't have any parameter that contains Summer so I am not sure if you can filter out Summer League games through the API.
https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md


Also here is the documentation that I originally wrote up detailing how I analyzed each endpoint. https://github.com/swar/nba_api/blob/master/docs/nba_api/tools/stats/endpoint_analysis/analysis.md

**Comment by PureMichael** [comment]
Im not sure if this was resolved but for the future I did this:

boxscore = boxscoresummaryv2.BoxScoreSummaryV2(game_id)
boxscore_dict = boxscore.get_normalized_dict()

if boxscore_dict['OtherStats'][0]['LEAGUE_ID']=='00':

LEAGUE_ID is '00' for regular season.
