### ISSUE TITLE
Update Slack Link in README

### ISSUE THREAD

**Issue by ZanePeycke** [swar/nba_api#361]
The [slack link in the readme](https://join.slack.com/t/nbaapi/shared_invite/zt-cayfrnfo-s9rySAmBXxBloL09S6N0KA) is no longer active, please update with a new link. 

On opening this link a new tab opens with the following message displayed:
"
This link is no longer active
To join this workspace, you’ll need to ask the person who originally invited you for a new link.
"

**Comment by rsforbes** [comment]
@ZanePeycke - This has been resolved. Thanks for the heads up.
