### ISSUE TITLE
[Bug]: Is there still a slack channel? The current link does not work

### ISSUE THREAD

**Issue by zhouzhang** [swar/nba_api#363]
### NBA API Version

V1.2.1

### Issue

The current link for slack channel does not seem to work? Is there still a slack channel for folks to join? Thank you!

**Comment by rsforbes** [comment]
@zhouzhang - I just signed out of Slack, used the link on the README.md, and was able to successfully redirect to Slack, get prompted for authentication, and successfully log in.

What error are you getting? Can you provide a screenshot and the link you are using?

We had an issue, but it should be fixed.

**Comment by zhouzhang** [comment]
@rsforbes I tried that signing out and using the link, it did not work. Here is the screen shot:
![Screenshot 2023-08-10 at 2 35 16 PM](https://github.com/swar/nba_api/assets/9957310/dd625ee5-b4bc-4802-bec6-28e5badec6f9)

**Comment by rsforbes** [comment]
@zhouzhang - I'm curious is something is cached by your browser. 

1. I opened a private session in my browser
2. I clicked the Slack Button on the README.MD: `https://join.slack.com/t/nbaapi/shared_invite/zt-20mqfii8j-FQDThxBl5gArcL4RBUL4yA`
3. I was redirected to `https://nbaapi.slack.com/join/shared_invite/zt-20mqfii8j-FQDThxBl5gArcL4RBUL4yA#/shared-invite/email`

If you notice in number three above, the redirect differs from what you are getting. Below is the result.

![image](https://github.com/swar/nba_api/assets/847338/9c50e3b7-cfd3-460b-8f6f-69f621517715)

**Comment by sidneypaulymer** [comment]
I get the same screen saying "This link is no longer active". When I manually enter the link address that you provided above, it works. It looks like the link in the README.md was changed somehow.

Link you gave: https://join.slack.com/t/nbaapi/shared_invite/zt-20mqfii8j-FQDThxBl5gArcL4RBUL4yA
Link currently in README.md: https://join.slack.com/t/nbaapi/shared_invite/zt-cayfrnfo-s9rySAmBXxBloL09S6N0KA

**Comment by rsforbes** [comment]
Thanks for pointing that out. I'll work on getting it fixed. Glad you could get in.

**Comment by rsforbes** [comment]
This has been resolved. It was an oversite on my part as the link is located within the Slack shield at the top of the page...and within the text. The shield was correct while the text was incorrect. All should be working now.
