### ISSUE TITLE
[Bug]: shotchartdetail not returning anything

### ISSUE THREAD

**Issue by bryanrussel-corona** [swar/nba_api#366]
### NBA API Version

1.2.1

### Issue

shotchartdetail worked a few months ago but now its not returning anything. is it code related or api-based?

**Comment by KerwinFuyihang** [comment]
Same problem, do you get any solution to it?

**Comment by rsforbes** [comment]
Looking into this. Do you have a sample call you can share? Also, do you have previous call that was working and no longer working?

**Comment by bryanrussel-corona** [comment]
def get_shot_data(player_full_name,context_measure,season_type,season):
    player_dictionary = players.get_players()
    player_info = [player for player in player_dictionary if player['full_name'] == player_full_name][0]
    player_id = player_info['id']
    player_shotlog = shotchartdetail.ShotChartDetail(player_id = player_id, 
                                                 context_measure_simple = context_measure,
                                                 season_type_all_star = season_type,
                                                 season_nullable=season)
    shot_data = json.loads(player_shotlog.get_json())
    return shot_data
   
   this is the function i was using before. its already integrated to my application so im not able to show that it works but i used this a few months ago. And no i dont have any call that i previously use that dont work anymore. i dont know if the problem is within the API or the shotchartdetail function from the program. For context i tried doing some sample calls like the one used on the example at this programs homepage and that worked 
from nba_api.stats.endpoints import playercareerstats

# Nikola Jokić
career = playercareerstats.PlayerCareerStats(player_id='203999') 

# pandas data frames (optional: pip install pandas)
career.get_data_frames()[0]

# json
career.get_json()

# dictionary
career.get_dict()

This code snippet worked

**Comment by KerwinFuyihang** [comment]
Hi Bryan, I think maybe you have to clarify the team ID as one of the input paramaters. I use the similar code as yours and get the same empty output as well. But when I modify the code like this, it works:
    @staticmethod
    def get_shot_data(id: int, team_ids: list, seasons: list) -> list:
        """ Get the shot data of a player from his id and seasons
        """
        from nba_api.stats.endpoints import shotchartdetail
        df = pd.DataFrame()
        for season in seasons:
            for team in team_ids:
                shot_data = shotchartdetail.ShotChartDetail(
                    team_id=team,
                    player_id=id,
                    context_measure_simple='FGA',
                    season_nullable=season
                )
                df = pd.concat([df, shot_data.get_data_frames()[0]])

        return df
        
        This is a part of the code (actually I compile several functions in one class), and hope you find it works.

**Comment by bryanrussel-corona** [comment]
yeah but before you dont need to specify that as i use it to rtetrieve lebrons shot chart for the entirety of his career just constantly calling that function. will try your solution still tho. Thanks

**Comment by Marco943** [comment]
> yeah but before you dont need to specify that as i use it to retrieve lebrons shot chart for the entirety of his career just constantly calling that function. will try your solution still tho. Thanks

Did it work for you? I still can't get it to work, even having specified team_id, player_id, contexto_measure_simple and season_nullable. Just empty response

**Comment by rsforbes** [comment]
@bryanrussel-corona - Are you still experiencing issues? I just closed an issue due to confusion around the `Season.default` parameter; it's a calculated value. Setting `season_nullable` solved that issue; perhaps that is the problem here. 

Try the following:
```
# ShotChartDetail
from nba_api.stats.endpoints.shotchartdetail import ShotChartDetail
shot_data = ShotChartDetail(
  team_id=1610612765,
  player_id=1631105,
  context_measure_simple='FGA',
  season_nullable="2022-23")
shot_data.get_data_frames()[0]
```
![image](https://github.com/swar/nba_api/assets/847338/cbcfe656-a45a-470d-92b8-810440e74b8a)
