### ISSUE TITLE
nba_api installed in IPython, but not globally?

### ISSUE THREAD

**Issue by bpisaacoff** [swar/nba_api#37]
Hi, thanks for making this API, it's super helpful. I'm a bit of a python noob (I do all of my development in Matlab), so please excuse me if this is a dumb question.

I've been using the nba_api a bunch in Spyder and it works great, however when I went to run a script in Anaconda prompt it didn't seem like nba_api had been installed. I got an error on my first call to nba_api that it did not exist.

Any idea what's going on here and how to fix it?

Thanks,

**Comment by swar** [comment]
This package is not a default package for Anaconda. So you would probably need to install it manually. 

https://conda.io/docs/user-guide/tasks/manage-pkgs.html

This page may help, I don't use Anaconda's python distribution so if this doesn't work please update.
