### ISSUE TITLE
[Bug]: Just local test, player career stats endpoint no respond

### ISSUE THREAD

**Issue by princeofforest** [swar/nba_api#387]
### NBA API Version

not sure

### Issue

I found this NBA API available, this is a great resource, I read the document, the end point about playercareerstats seem no respond, i just copied and pasted this link to postman https://stats.nba.com/stats/playercareerstats?LeagueID=&PerMode=Totals&PlayerID=2544, Am i missing something? please advise, thanks a lot!

**Comment by rsforbes** [comment]
@princeofforest - I just ran this call through Google Colab and Postman. Both worked as expected.

Google Colab
![image](https://github.com/swar/nba_api/assets/847338/10e20a9b-a01f-4fed-bd44-c00a73e938d5)

Postman
![image](https://github.com/swar/nba_api/assets/847338/9d507191-fde2-43b7-a78e-4c2dfd6ea5ff)

Postman Headers
![image](https://github.com/swar/nba_api/assets/847338/8e258809-ff4b-4741-aaa1-232d2abbffc2)
