### ISSUE TITLE
See FG% allowed per team, based on shot type/distance? 

### ISSUE THREAD

**Issue by ericsiyuanma** [swar/nba_api#40]
Is there away to do this? I can't seem to find a way. Preferably a way to filter by number of games or time range

**Comment by swar** [comment]
I'm not sure if there is an endpoint that contains this aggregated information.
https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguedashplayershotlocations.md

If that link doesn't help, you will need to grab all shot chart details for both teams and calculate the distance using X/Y and whether the shot was made or missed.
