### ISSUE TITLE
Any team offensive efficiency stats??

### ISSUE THREAD

**Issue by shaun2416** [swar/nba_api#41]

**Comment by shaun2416** [comment]
Seems to be deprecated, damm

**Comment by swar** [comment]
@shaun2416 

According to ESPN the definition of Offensive Efficiency is stated below.

```
OFF EFF: Offensive Efficiency - the number of points a team scores per 100 possessions.
```


Doing a quick ctrl+f for 'Per100' and I see a bunch of endpoints that can calculate data based on 100 possessions.

In your case, you would want to use [LeagueDashTeamStats](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguedashteamstats.md) and change the `per_mode_detailed` python variable to `"Per100Possessions"`.

I think this should get you what you need.
