### ISSUE TITLE
A Little Help: How to pull player "playtype" stats. Is there an endpoint?

### ISSUE THREAD

**Issue by jwall5678** [swar/nba_api#416]
### NBA API Version

1.4.1

### Issue

I am struggling to find how to pull the play type stats from NBA.com. The stats I'm looking for are housed here (https://www.nba.com/stats/players/isolation). Is there an endpoint to include this data?

**Comment by marcelcastrolima** [comment]
What exactly do you mean by type? You can get stats similar to the one you linked using the playercareerstats endpoint.

```
lebron = playercareerstats.PlayerCareerStats(player_id='2544') 
lebron = lebron.get_data_frames()[0]
lebron
```
