### ISSUE TITLE
Question: Team defensive stats vs position

### ISSUE THREAD

**Issue by msimoni18** [swar/nba_api#417]
I'm actively searching for an endpoint that would provide how well a team does defensively vs different positions. I haven't found anything yet, so I figured I'd ask here while I continue looking. 

Using points as an example, the Celtics are ranked 1 defensively against PG (meaning PGs score the least amount of points against the Celtics relative to the rest of the teams in the NBA) and centers score a lot of points against the Celtics relative to the rest of the teams.

| Team                | Defensive Rank | Position  |
|--------------|----------------|---------|
| Boston Celtics | 1                      | PG           |
| Boston Celtics | 29                         | C             |

**Comment by msimoni18** [comment]
For anyone who has a similar question, I found a solution:

```
stats = nba.leaguedashteamstats.LeagueDashTeamStats(
    measure_type_detailed_defense='Opponent',
    per_mode_detailed='PerGame',
    player_position_abbreviation_nullable='G'
)

df = stats.get_data_frames()[0]
```

Note that even though the documentation for this [endpoint](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguedashteamstats.md) says you can input `((F)|(C)|(G)|(C-F)|(F-C)|(F-G)|(G-F))?`, only `((F)|(C)|(G))?` works.

**Comment by girishm010** [comment]
Did you figure how to get the (C-F)|(F-C)|(F-G)|(G-F) inputs to work?

**Comment by msimoni18** [comment]
@girishm010 No, I never figured it out. My guess is maybe something with the endpoint changed and those are no longer valid options, but I'm not 100% sure.
