### ISSUE TITLE
works on local flask server but not on GCP?

### ISSUE THREAD

**Issue by nichu96** [swar/nba_api#419]
### NBA API Version

v11111

### Issue

![image](https://github.com/swar/nba_api/assets/20098158/9dd025f7-3c03-4b5e-9709-867ea12129e7)

it works perfect on my local server but not working on hosting with error like above ^
any ideas guys ?

**Comment by OnerInce** [comment]
There is a very detailed conversation about it: https://github.com/swar/nba_api/issues/176
Basically, NBA is blocking access from popular cloud providers (AWS, GCP etc.). You can use custom proxies to bypass it

**Comment by nichu96** [comment]
> There is a very detailed conversation about it: #176 Basically, NBA is blocking access from popular cloud providers (AWS, GCP etc.). You can use custom proxies to bypass it

can u link any confirmed proxies and tutorial how to avoid it ?

**Comment by OnerInce** [comment]
> > There is a very detailed conversation about it: #176 Basically, NBA is blocking access from popular cloud providers (AWS, GCP etc.). You can use custom proxies to bypass it
> 
> can u link any confirmed proxies and tutorial how to avoid it ?

You have to pay for working proxies. There are many proxy providers, you can find one with a simple search.
