### ISSUE TITLE
Slack 

### ISSUE THREAD

**Issue by mxufc29** [swar/nba_api#423]
Is there still an active Slack channel for nba_api? Tried the invite in the readme but looks like it has expired. Anyone know of any other collaboration channels for for those working on analytics projects? Thanks!

**Comment by rsforbes** [comment]
Yes. Please post the link you are using. It should be set to never expire.

**Comment by rsforbes** [comment]
@mxufc29 - I've updated the README.md. Please test and let me know if it's resolved.

**Comment by mxufc29** [comment]
@rsforbes Yes link works now, just joined, thanks for updating!
