### ISSUE TITLE
Starting Lineups

### ISSUE THREAD

**Issue by girishm010** [swar/nba_api#425]
I was wondering if there was any way to get the starting lineups for games on the day of the request. I see that NBA has it on https://www.nba.com/players/todays-lineups but I am unable to find anything that can pull that information in the API. Maybe even a way to get the most recent starting lineup or the lineup used last game would work too! Thanks

**Comment by rsforbes** [comment]
@girishm010 - We currently do not include that within the library, though it could fit within the Live section. Chrome Dev Tools shows the link as `
https://stats.nba.com/js/data/leaders/00_daily_lineups_20240213.json` which is easy enough to incorporate. 

Marking this as an enhancement for review.

**Comment by SrijithVenkat** [comment]
This JSON was super easy to use! Thank you!
