### ISSUE TITLE
[Bug]: Why are there decimals in fields that should not have decimals? For example, opponent points. 

### ISSUE THREAD

**Issue by SrijithVenkat** [swar/nba_api#428]
<img width="160" alt="Screenshot 2024-02-14 at 10 58 56 PM" src="https://github.com/swar/nba_api/assets/95888452/aeace35b-1f79-4798-b4f2-162c93a32393">
### NBA API Version

V1.4.1

### Issue

<img width="165" alt="Screenshot 2024-02-14 at 10 54 42 PM" src="https://github.com/swar/nba_api/assets/95888452/ee4a70ed-3c1c-46f8-9838-e37cb214c91e">

Why are there decimals in fields that should not have decimals? For example, opponent points (26 in the picture) is a start, but there are a few more.
 
Even if my games are the last 2, for 2 whole numbers to equal out to 20.9 is simply not plausible. I also saw this trend when I set last_n_games="1". Is this simply user error on my part on how I am utilizing leaguedashteamstats? or is this a bug? 

Thanks

### Code

season_game_stats = LeagueDashTeamStats(
    measure_type_detailed_defense='Opponent',
    per_mode_detailed='PerGame',
    player_position_abbreviation_nullable='C',
    season='2023-24',
    last_n_games="2",
)

**Comment by rsforbes** [comment]
PerGame returns an average. Use [Totals](https://github.com/swar/nba_api/blob/b25107891ecb86cb385c9dc6c2b79e7c08d31c06/src/nba_api/stats/library/parameters.py#L443).

**Comment by SrijithVenkat** [comment]
<img width="214" alt="Screenshot 2024-02-15 at 11 31 39 AM" src="https://github.com/swar/nba_api/assets/95888452/03157df9-0224-4d1c-be2b-1cbe392a5e58">
Even using "Totals" for last_n_games = 1, results in decimals. 

Also, to my understanding the PerGame average of 1 game should be whole numbers anyway no?

**Comment by rsforbes** [comment]
You'd certainly expect whole numbers on totals or n=1. We don't control the
data response as we just expose the endpoint. I'll take a look over
the weekend and see what the actual stats pages are showing.

**Comment by SrijithVenkat** [comment]
I appreciate your help on this! So, I checked it and the only difference between PerGame and Totals returning decimals, and the NBA website is rounding. So, I just added a round to fix the "issue". Thanks once again!
