### ISSUE TITLE
CommonAllPlayers for current season ONLY incomplete

### ISSUE THREAD

**Issue by denutza** [swar/nba_api#43]
Using the commonallplayers endpoint, and parameter is_only_current_season=1 for both '2016-17' and '2017-18' seasons, both return only 108 unique players for each respective season.

CommonAllPlayers(league_id=LeagueID.default,season='2016-17',is_only_current_season=1)

I think setting is_only_current_season=0 works (which results I believe are in the Data file, and return over 4000 players), but i want to get each season individually.

Is this a known inconsistency with many of the endpoints? Or do I have a parameter set wrong?

**Comment by swar** [comment]
@denutza 

I believe this is a known inconsistency. Or a misrepresentation on parameters. IsOnlyCurrentSeason I believe refers to players that last played in that season?

This is very inconsistent and you might have better luck cross referencing players with gamelogs so you have a complete picture of what seasons they played in. However, there might be a more efficient solution that I am not aware of.
