### ISSUE TITLE
Can't run Playergamelog in Postman

### ISSUE THREAD

**Issue by bateou25** [swar/nba_api#450]
Hi,

It's my first time using the API and I tried out the PlayerGameLog endpoint URL in Postman using my local but it does not return anything.

I tried calling the API through the default endpoint URL from https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playergamelog.md

<img width="493" alt="image" src="https://github.com/swar/nba_api/assets/7238639/8fa7978e-2324-422c-aa13-13139ea90562">

**Comment by rsforbes** [comment]
Try the following:

Single Game
`https://stats.nba.com/stats/playergamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=0&LeagueID=00&Location=&MeasureType=Base&Month=0&OppTeamID=0&OpponentTeamID=0&Outcome=&PORound=0&PaceAdjust=N&PerMode=Totals&Period=0&PlayerID=1631105&PlusMinus=N&Rank=N&Season=2022-23&SeasonSegment=&SeasonType=Regular Season&ShotClockRange=&TeamID=&VsConference=&VsDivision=`

Mutliple Games
`https://stats.nba.com/stats/playergamelogs?DateFrom=&DateTo=&GameSegment=&LastNGames=&LeagueID=&Location=&Month=&Outcome=&PORound=&PerMode=&Period=&PlayerID=&Season=2023-24&SeasonSegment=&SeasonType=Regular+Season&ShotClockRange=&TeamID=&VsConference=&VsDivision=`
