### ISSUE TITLE
Accessing player boxscores

### ISSUE THREAD

**Issue by A00N** [swar/nba_api#453]
I am trying to gather player data from each game like this: https://www.nba.com/stats/players/boxscores?SeasonType=Regular+Season

But i cannot seem to find a way to do it.

For regular game data I did: data = leaguegamelog.LeagueGameLog(league_id="00", season=season_str).get_data_frames()[0]

Any suggestions?

**Comment by awpt-alt** [comment]
You need to pass this parameter to fetch the player data, the default param is fetching team data.

`player_or_team_abbreviation=PlayerOrTeamAbbreviation.player`
