### ISSUE TITLE
[Bug]: get_wnba_teams() doesn't work?

### ISSUE THREAD

**Issue by rj7002** [swar/nba_api#456]
### NBA API Version

V1.5.0
### Issue

I tried to use the get_wnba_teams() method from the static teams class but it seems like it doesn't exist. Is there any way you can fix this

**Comment by sharifhsn** [comment]
I just ran it on my own machine and it worked fine. Is this the only method that is not working fo ryou?

**Comment by rj7002** [comment]
Yeah, it doesn't show up as an available method. Could you share your code so I can see how you ran it?

**Comment by sharifhsn** [comment]
This should work:
```
from nba_api.stats.static import teams
print(teams.get_wnba_teams())
```

**Comment by rsforbes** [comment]
I could not reproduce the issue.

Google Colab Code
```
!pip install nba_api
from nba_api.stats.static import teams
teams.get_wnba_teams()[0]
```

Output
```
{'id': 1611661313,
 'full_name': 'New York Liberty',
 'abbreviation': 'NYL',
 'nickname': 'Liberty',
 'city': 'New York',
 'state': 'New York',
 'year_founded': 1997}
```
