### ISSUE TITLE
[Bug]: ScoreBoard endpoint + ScoreBoardv2 endpoint do not work

### ISSUE THREAD

**Issue by leandronesi** [swar/nba_api#464]
### NBA API Version

1.5.0

### Issue

I tried to use both Scoreboard and ScoreBoardV2 endpoints, but i did not succeed in make them work. 

The error I'm encountering is list index out of range. 

My code run with a lot of endpoints, so i really don't understand why these are not working at all. 

Please can you help? 

### Code

from nba_api.stats.endpoints import ScoreboardV2
import pandas as pd
def fetch_nba_schedule(date='2023-10-25'):
    # Call the ScoreboardV2 endpoint
    scoreboard = ScoreboardV2(
        league_id='00',  # '00' for NBA
        game_date=date
    )
    
    # Get data frames
    data_frames = scoreboard.get_data_frames()
    return data_frames
data_frames = fetch_nba_schedule(date='2023-10-25')

**Comment by a3jeu** [comment]
I have the same issue

`    if isinstance(self.data["headers"][0], str):
                  ~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range`

**Comment by rsforbes** [comment]
@a3jeu / @leandronesi - I have a coded up a fix for this. Other issues need resolving. Release expected in 24hrs.
