### ISSUE TITLE
[Bug]: KeyError: 'resultSet' - even from Documentation Jupyter Example Code 

### ISSUE THREAD

**Issue by arno23o** [swar/nba_api#469]
### NBA API Version

V1.4.1

### Issue

I'm trying to access PlaybyPlay data through the NBA_API but keep getting a KeyError: 'resultSet'

To troubleshoot, I reverted back to a simple example that is provided in the API documentation (pasted below and link to relevant section of documentation) - but this still produces the same error. Just a few days ago, this error was not happening: the pasted code worked without issue.

```
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2('20301180').get_data_frames()[0]
pbp.head()
```

([API Documentation, Jupyter Notebook Example Code](https://github.com/swar/nba_api/blob/master/docs/examples/Finding%20Games.ipynb) (^ Scroll to very last example on the page)

### Code

from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2('20301180').get_data_frames()[0]
pbp.head()

**Comment by rsforbes** [comment]
@arno23o - The NBA uses two leading zeros for the GameID.

```
from nba_api.stats.endpoints import playbyplayv2
pbp = playbyplayv2.PlayByPlayV2('0020301180').get_data_frames()[0]
pbp.head()
```
