### ISSUE TITLE
[Docs] The Slack invitation link has expired

### ISSUE THREAD

**Issue by kattakaha** [swar/nba_api#471]
## Summary

It seems that the Slack invitation link mentioned in the README has expired and is no longer usable. I would appreciate it if you could check this.

## Link

https://github.com/swar/nba_api/blob/4375b0e947842759cf614cafed2e3ba4d40ab20e/README.md?plain=1#L76

## Screenshot
![image](https://github.com/user-attachments/assets/7800f2b3-d678-4bf3-a978-966059895aaf)

**Comment by JohnMikko27** [comment]
Hi, can I work on this? I'm pretty new here and would like to contribute.

**Comment by kattakaha** [comment]
@JohnMikko27 Hi. That sounds good. If you can do it, please go ahead. However, I anticipate that you will not be able to issue an invitation link unless you are the owner of the Slack workspace or have the necessary permissions.

**Comment by rsforbes** [comment]
@JohnMikko27  - Thanks for the work here.
