### ISSUE TITLE
API always times out

### ISSUE THREAD

**Issue by Geno16** [swar/nba_api#472]
The API always returns a 403 when requesting "scoreboardv2" data. This occurs both if I use the URL directly, and if using this library. I encountered this issue after running only one query after over 8 hours of time where I issued no queries. If it matters, I had previously installed the requests library long before installing this library. How do I actually get the data? What am I doing wrong?

                scoreboard = scoreboardv2.ScoreboardV2(game_date=date.isoformat())
                games = scoreboard.get_data_frames()[1]

This is using the library where "date" is a python date object. It always time out.

                import requests as R
                URL = "http://data.nba.com/data/5s/json/cms/noseason/scoreboard/2023-11-11/games.json"
                r = R.get(URL)

I tried this after, and it returned HTTP code 403. I also tried it with the date having no spaces.

**Comment by Geno16** [comment]
The basic box score endpoint works. No other box score endpoint works, though.

**Comment by rsforbes** [comment]
@Geno16 - Apologies for missing the deprecation of Scoreboard from the release notes. v1.6.0 no longer supports this call.

**Comment by mrwrob** [comment]
@rsforbes the same issue (timeout) occurs with LeagueGameLog. I used it to get upcoming games, is there another way to get the games scheduled for a given date?

**Comment by rsforbes** [comment]
@mrwrob - Just ran this from Google Colab and Postman. All results returned without issue. 

Note: In case you are running from the cloud, the NBA blocks all traffic.

### Google Colab
```
from nba_api.stats.endpoints.leaguegamelog import LeagueGameLog
LeagueGameLog(season='2023-24').get_data_frames()[0]
```

![image](https://github.com/user-attachments/assets/91545a23-d854-4018-8c35-b3b43c54e7a7)

### Postman
`https://stats.nba.com/stats/leaguegamelog?Counter=30000&DateFrom=&DateTo=&Direction=DESC&LeagueID=00&PlayerOrTeam=P&Season=2023-24&SeasonType=Pre Season&Sorter=DATE`

![image](https://github.com/user-attachments/assets/f227b783-0c69-4dfb-b644-fcb9f691c507)
