### ISSUE TITLE
Feature: Bump certifi to 2024.8.30

### ISSUE THREAD

**Issue by compdesigner-nz** [swar/nba_api#476]
### NBA API Version

1.6.0

### Issue

I am using poetry within a project and I am getting a `poetry add` issue when trying to add `nba_api` as I am getting a pip conflict with a pre-existing version of certifi. This can be resolved by bumping `certifi` to at least 2024.8.30.

Thanks

**Comment by rsforbes** [comment]
@compdesigner-nz - This should be resolved. Just tested on Google Colab. Thanks for the heads up.

**Comment by compdesigner-nz** [comment]
Legend, tysm
