### ISSUE TITLE
[Bug]: Issue with Inactive Rookies in Active Players Data

### ISSUE THREAD

**Issue by flintitit** [swar/nba_api#482]
### NBA API Version

1.5

### Issue

Some of the active players, particularly rookies, appear to be marked as inactive. 
For example, player data shows: {'id': 1641744, 'full_name': 'Zach Edey', 'first_name': 'Zach', 'last_name': 'Edey', 'is_active': False}.

Do you have an updated version of the active players data?

Thanks for providing this API, it's been really helpful

**Comment by nichu96** [comment]
@swar  Are you planning any update?

Here are just the names of the rookies.

1. Zaccharie Risacher
2. Alex Sarr
3. Reed Sheppard
4. Stephon Castle
5. Ron Holland II
6. Tidjane Salaun
7. Donovan Clingan
8. Rob Dillingham
9. Zach Edey
10. Cody Williams
11. Matas Buzelis
12. Bub Carrington
13. Cam Christie
14. Isaiah Collier
15. AJ Johnson
16. Tristan Da Silva
17. Yves Missi
18. Ajay Mitchell
19. Jared McCain
20. Tyler Kolek
21. Dalton Knecht
22. Baylor Scheierman
23. Jaylon Tyson
24. Jaylen Wells
25. Kel'el Ware
26. Tristen Newton
27. Kyshawn George
28. Ryan Dunn
29. Jamal Shead

**Comment by rsforbes** [comment]
@nichu96 - We only update the static file during library updates/patches. The intent of the file is quite limited, focusing more on the caching of player names to prevent recurrent calls to the endpoints. There are a couple PRs in review. When they complete the cycle and I send out a new release, I'll likely update the file. 

If it's something you'd like to submit a PR for, I'm happy to merge the update (though when it'll release would be TBD).

The file that refreshes the file can be found here: `tools/stats/static_players_update/update.py`
