### ISSUE TITLE
Is there an API to get livescore data about players? Points, rebounds and so on...

### ISSUE THREAD

**Issue by mvrebolo** [swar/nba_api#483]
### NBA API Version

last version

### Issue

I would like to get livescore about team and players during the game, is it possible?

**Comment by wild-bill** [comment]
Have you tried the [Live endpoints](https://github.com/swar/nba_api/tree/master/docs/nba_api/live/endpoints)? You can find some documentation on how to use them [here](https://github.com/swar/nba_api/blob/master/docs/examples/LiveData.ipynb).

**Comment by mvrebolo** [comment]
@wild-bill it worked as I would like. Thank you.
