### ISSUE TITLE
API call getting stuck, no timeout error or anything similar

### ISSUE THREAD

**Issue by bpisaacoff** [swar/nba_api#49]
Hi swar, thanks for making this it's great.

I keep having this problem where my scripts will occasionally get stuck at the API call, even though the same command completes when I run it manually in the python command window. Any idea why this is happening?

Secondarily, I tried to write some code to retry the command in this case when it gets stuck. Though the code works great for all my tests, for some reasons when this problem with the API happens it doesn't work, any idea why this is?
   The code to retry after a time limit is below. It's pretty gross franken-code, that I cobbled together from StackOverflow (python is not my strength)

```python
class TimeoutException(Exception):
    def __init__(self, msg=''):
        self.msg = msg

@contextmanager
def time_limit(seconds, msg=''):
    timer = threading.Timer(seconds, lambda: _thread.interrupt_main())
    timer.start()
    try:
        yield
    except KeyboardInterrupt:
        raise TimeoutException("Timed out for operation {}".format(msg))
    finally:
        # if the action ends in specified time, timer is canceled
        timer.cancel()

## Example call to API which doesn't properly trigger my timer wrapping ##

successful=None
while successful is None:
    try:
        with time_limit(4,'sleep'):
            cur_teamR=commonteamroster.CommonTeamRoster(team_id=nba_teams[jj]['id'], season=cur_seas).get_data_frames()
            successful=3.1415
    except:
        print('Timeout pass')
        pass
```

**Comment by eswan18** [comment]
I am having a very similar problem even when running the package tests. I wonder if it is caused by the NBA site not responding if we issue too many requests too quickly? I don't know enough about web services to have a strong grasp of the issue.

**Comment by swar** [comment]
First thing, I apologize for the long delay in my response. I completely did not see this issue.

This is definitely a response on NBA's end that causes requests to timeout when we send subsequent requests without pausing in-between. I firstly recommend you adding in a way to pause between requests.

Secondly, I am classifying this issue now as a bug. In the next release, I am planning on adding custom header and proxy support on each request. In addition to that, I will add timeout as another value to pass in. Right now, I did not indicate a timeout for the requests library and thus it will forever hang until it finally connects and receives a response.

**Comment by bpisaacoff** [comment]
Great, that would all be really helpful. Thank you so much

**Comment by swar** [comment]
Added as of [v1.1.1](https://github.com/swar/nba_api/releases/tag/v1.1.1)
