### ISSUE TITLE
Can I get missed shot in shot chart detail endpoint ?

### ISSUE THREAD

**Issue by Xuan0504** [swar/nba_api#50]
I can only get MADE SHOOT using the endpoint ? Is that any way that I can get the MISSED SHOT too ? Thanks.

**Comment by swar** [comment]
https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/shotchartdetail.md

You will need to change the `context_measure_simple` variable. Unfortunately, there is no way to filter for just MISSED SHOTs, so you need to change that variable to 'FGA' to get all Field Goal Attempts and then you can just filter out the MADE SHOTs.
