### ISSUE TITLE
Newly Discovered Endpoints

### ISSUE THREAD

**Issue by swar** [swar/nba_api#54]
Thanks to an email from Aymen (no idea your GitHub username), he has identified a new endpoint: LeagueSeasonMatchups.

I plan on adding this Endpoint this weekend so stay tuned. Also more changes should be coming this weekend, I might hold off on the documentation website but make more progress on it this weekend. 

Source: https://stats.nba.com/player/2544/matchups/?sort=POSS&dir=1
Example: https://stats.nba.com/stats/LeagueSeasonMatchups?DateFrom=&DateTo=&LeagueID=00&OffPlayerID=2544&Outcome=&PORound=0&PerMode=PerGame&Season=2018-19&SeasonType=Regular+Season

**Comment by AyKay10** [comment]
Hi Swar, 
thank you for making this great work! I appreciate your reactivity!
there is another endpoint i found; the BoxScore Matchups between players in a certain Game:
- boxscorematchups
- https://stats.nba.com/stats/boxscorematchups?GameID=0021801180
- https://stats.nba.com/game/0021801180/matchups/

**Comment by swar** [comment]
Other new endpoints

* AssistLeaders
* AssistTracker
* BoxScoreDefensive
* FantasyWidget
* FranchiseLeaders
* FranchisePlayers
* LeaguePlayerOnDetails
* TeamAndPlayersVsPlayers
* WinProbabilityPBP

**Comment by swar** [comment]
Added as of v1.1.1
