### ISSUE TITLE
Only 2018 games avaiable?

### ISSUE THREAD

**Issue by kramer425** [swar/nba_api#58]
```python
game_finder = leaguegamefinder.LeagueGameFinder()
games_df = game_finder.get_data_frames()[0]
games_df = games_df[games_df.SEASON_ID.str[-4:] != str(2018)]
len(games_df)
```

> 0

Am I doing something wrong/ is there any way to get the game data for previous years?

Edit: 
`games_df = game_finder.get_data_frames()[0]`
was obviously the issue

**Comment by kramer425** [comment]
Is there any way to pass a season with a specific year to LeagueGameFinder?

**Comment by swar** [comment]
Add a `season_nullable` parameter to the original call. 

Documentation for LeagueGameFinder can be found here: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguegamefinder.md

Documentation for the `season_nullable` parameter can be found here: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md#Season

**Comment by kramer425** [comment]
Thanks for your reply. My apologies but I do not know python that well -- how do I construct a Season with a specific year? I don't see any init methods in Season/SeasonYear.

**Comment by swar** [comment]
Change this line to be something similar to this:

```
game_finder = leaguegamefinder.LeagueGameFinder(season_nullable='2018-19')
# or
game_finder = leaguegamefinder.LeagueGameFinder(season_nullable='2017-18')
```

You can replace it with whatever season you need.

**Comment by kramer425** [comment]
Thanks, never seen passing a string as a class before.

**Comment by rsforbes** [comment]
@a4v2d4 - All data is managed by the NBA.
