### ISSUE TITLE
stats.nba.com: LeagueDashPtStats not mapped

### ISSUE THREAD

**Issue by 903124** [swar/nba_api#6]
leaguedashptstats in [players tracking ](https://stats.nba.com/players/drives/) not mapped

**Comment by swar** [comment]
Will add this endpoint sometime this week or next week when I get a chance to research: https://github.com/swar/nba_api/issues/4

**Comment by swar** [comment]
Added endpoint in commit https://github.com/swar/nba_api/commit/437543e3c3907cde2ce09900b6450c2aa0d30723

Slotted to release this endpoint in next release. Unless I get distracted, it will happen tomorrow.

**Comment by swar** [comment]
This is active as of [`v1.0.5`](https://github.com/swar/nba_api/releases/tag/v1.0.5).
