### ISSUE TITLE
How to get video given event?

### ISSUE THREAD

**Issue by slizb** [swar/nba_api#61]
I've tried:

```
from nba_api.stats.endpoints import videoevents

game_id = 0021801220
event_id = 7
video_event = videoevents.VideoEvents(game_id, event_id)
video_specs = video_event.nba_response.get_dict()
print(video_specs)
```
which returns:
```
{'resource': 'videoevents', 'parameters': {'GameID': '0021801220', 'GameEventID': 7}, 'resultSets': {'Meta': {'videoUrls': [{'uuid': '81066fa9-93b2-76d4-5e78-7bbe89335bc4', 'dur': '0.040000', 'stt': 'thumbnail,thumb_nba14,desktop', 'stp': 'http://nba.cdn.turner.com/nba/big/nba/wsc/2019/04/11/81066fa9-93b2-76d4-5e78-7bbe89335bc4.nba_3_320x180.jpg', 'sth': 180, 'stw': 320, 'mtt': 'thumb_nba1,thumbnail,desktop', 'mtp': 'http://nba.cdn.turner.com/nba/big/nba/wsc/2019/04/11/81066fa9-93b2-76d4-5e78-7bbe89335bc4.nba_3_576x324.jpg', 'mth': 324, 'mtw': 576, 'ltt': 'thumbnail,thumb_nba12,desktop', 'ltp': 'http://nba.cdn.turner.com/nba/big/nba/wsc/2019/04/11/81066fa9-93b2-76d4-5e78-7bbe89335bc4.nba_3_1280x720.jpg', 'lth': 720, 'ltw': 1280}]}, 'playlist': [{'gi': '0021801220', 'ei': 7, 'y': 2019, 'm': '04', 'd': '10', 'gc': '2019-04-10/INDATL', 'p': 1, 'dsc': "Collison 14' Pullup Jump Shot (2 PTS) (O'Quinn 1 AST)", 'ha': 'ATL', 'va': 'IND', 'hpb': 0, 'hpa': 0, 'vpb': 0, 'vpa': 2, 'pta': 1}]}}
```

None of the url's in these results are actually videos, only .jpg thumbnails. Is it possible to retrieve the video url or construct it from other sources in `nba_api`? For example, this:

https://pmd.cdn.turner.com/nba/big/nba/wsc/2019/04/11/81066fa9-93b2-76d4-5e78-7bbe89335bc4.nba_3662832_1920x1080_5904.mp4

**Comment by swar** [comment]
It is definitely possible. Looking at the requests for the page: 


https://secure.nba.com/video/wsc/league/81066fa9-93b2-76d4-5e78-7bbe89335bc4.secure.xml

You need to feed this the uuid into following URL in order to get it to show you a response with all the video information.

**Comment by swar** [comment]
It is definitely possible. Looking at the requests for the page: https://stats.nba.com/events/?flag=3&CFID=&CFPARAMS=&PlayerID=201954&TeamID=1610612754&GameID=0021801220&ContextMeasure=FGM&Season=2018-19&SeasonType=Regular%20Season&RangeType=0&StartPeriod=1&EndPeriod=10&StartRange=0&EndRange=28800&section=game&sct=plot

You can see that an additional request is made to get an XML page that contains the link to the URLs.

Link: https://secure.nba.com/video/wsc/league/81066fa9-93b2-76d4-5e78-7bbe89335bc4.secure.xml

You will need to feed the uuid into above URL in order to get it to show you a response with all the video information. This is not built-in to nba_api.

**Comment by slizb** [comment]
awesome, thanks for the quick response!

**Comment by myolaychit71-pixel** [comment]
<img width="672" height="1536" alt="Image" src="https://github.com/user-attachments/assets/c5d0f998-0bf7-4d99-9386-9e67a956c2d1" />

**Comment by myolaychit71-pixel** [comment]
### 

1. [ ] [**__**](

> url

)

**Comment by myolaychit71-pixel** [comment]
#591

**Comment by aarongiddings** [comment]
> It is definitely possible. Looking at the requests for the page: https://stats.nba.com/events/?flag=3&CFID=&CFPARAMS=&PlayerID=201954&TeamID=1610612754&GameID=0021801220&ContextMeasure=FGM&Season=2018-19&SeasonType=Regular%20Season&RangeType=0&StartPeriod=1&EndPeriod=10&StartRange=0&EndRange=28800&section=game&sct=plot
> 
> You can see that an additional request is made to get an XML page that contains the link to the URLs.
> 
> Link: https://secure.nba.com/video/wsc/league/81066fa9-93b2-76d4-5e78-7bbe89335bc4.secure.xml
> 
> You will need to feed the uuid into above URL in order to get it to show you a response with all the video information. This is not built-in to nba_api.

I was utilizing the 'VIDEO_AVAILABLE_FLAG' field in playbyplayv2 to obtain readily available clips from the NBA's website for an action recognition project that I am working on.  With the deprecation of playbyplayv2, does anyone have a suggested workaround?  I was expanding the categories for clip-labelling when playbyplayv2 went down, so I have not been able to test this latest version of the code.

[video_scrape_testv3.ipynb](https://github.com/user-attachments/files/24568069/video_scrape_testv3.ipynb)
