### ISSUE TITLE
Allow User Contributions to Endpoint Documentations

### ISSUE THREAD

**Issue by TK05** [swar/nba_api#72]
Figured we'd move this request into it's own issue, continuation of https://github.com/swar/nba_api/issues/32 and I'm sure elsewhere.

Please share ideas of what you think would be an appropriate way to share and display this information. 

Some initial ideas I had.
* Allow users to add known patterns for parameters with no known patterns.
* A place with links to the stats hub that make use of an endpoint.
  * For instance, https://stats.nba.com/players/traditional/?sort=PTS&dir=-1 uses LeagueDashPlayerStats
  * https://stats.nba.com/teams/shots-touch-time/ uses LeagueDashTeamPtShot
  * etc...
* A summary of the endpoint.
* A place for example usages of the endpoint and a short explanation for the type of data this use would return.

**Comment by swar** [comment]
Thinking through the logistics of the best way to represent the data would be best as we have discussed. It's just going to be a bit tricky to incorporate it into the auto-updating documentations. The best thing I can think of is adding a separate section where it's "User Defined Notes" where we store it in a JSON and append it to the existing documentation when we do something auto-updating.
