### ISSUE TITLE
PlayerVsPlayer doesn't work.

### ISSUE THREAD

**Issue by nista1111** [swar/nba_api#75]
When I use playervsplayer,
variable = playervsplayer.PlayerVsplayer(arguments are same as under code).
But error said "function' object has no attribute 'PlayerVsPlayer' ".
So, I wrote variable = playervsplayer(player_id,opponent_team_id,vs_player_id,season).
=>TypeError: playervsplayer() got an unexpected keyword argument 'vs_player_id'.

Please tell me how to use this function.
thanks.

**Comment by kalebmcgregor** [comment]
Hey nista1111,

Just to help me understand can you paste the full code block that you are using? The following worked for me on Python 3:
```python
from nba_api.stats.endpoints import playervsplayer
pvp = playervsplayer.PlayerVsPlayer(2543, 2542)
```

**Comment by nista1111** [comment]
Hey kalebmcgregor
I wrote 
```python
pvp = playervsplayer.PlayerVsPlayer(player_id=202691,opponent_team_id=1610612744,vs_player_id=202695,season="2018-19")
```
[I checked argument here](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playervsplayer.md)
I wanted to know playtime that klay and the other teammate are on court by each player.
(sorry for terrible English)
But I notice that this function doesn't solve my problem and opponent_team_id was unnecessary.
So, I will find other way.
Thank you for your answer kalebmcgregor.

**Comment by swar** [comment]
@nista1111 You haven't set the season_type_playoffs parameter to `Playoffs`

The API defaults to `Regular Season` and Kawhi did not play against the Warriors in the regular season.

The below should work

python```
pvp = playervsplayer.PlayerVsPlayer(player_id=202691, vs_player_id=202695, season="2018-19", season_type_playoffs="Playoffs")
```

**Comment by nista1111** [comment]
@swar 
Thank you for your replying.
Actually, I found my mistake. Very sorry for your taking time.
this package is really awesome.
I am proud of you. Thank you.
sayonara.
