### ISSUE TITLE
Question about use, small issue, and player search suggestion

### ISSUE THREAD

**Issue by SpecCRA** [swar/nba_api#76]
Hi everyone, 

**Starting with the small issue:** 

https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/static/players.md

The end points for `get_active_players()` and `get_inactive_players()` don't seem to work yet. 

**About use:**

I see there are endpoints for both `ShotChartDetail` and `ShotChartLineupDetail`. What is the difference between the two? They look just about identical. 

And is there a way to grab shot locations team by team rather than by just a single player? 

**Player search suggestion:** 

How about another search to grab a list of active players by a particular season? So for instance, we want to grab a list of players in the 2015-16 season. Right now, it feels like we need an outside source to scrape together this information. 

My solution has been the basketball-reference site, but that itself requires a bit of cleaning to match with this API. 

Thanks in advance!

**Comment by swar** [comment]
1.) What nba_api version are you on? That feature is only available in the newest version.

2.) ShotChartLineupDetail doesn't seem to give you shot chart details, just averages. This was just from a few tries. It also does not accept PlayerID as an argument. No idea about other differences or why the NBA made them.

You can get an entire team's shotchart by entering an empty PlayerID and just having a populated TeamID: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/shotchartdetail.md

3.) This is out of the scope of the library. Unfortunately this type of information would be very intensive to log into the program and maybe it's something that we can add in the future if it's easy enough to store. As of right now, I believe you should be able to make a script to save a static list of of players that played in a given Season. I don't believe there's an easy way other than finding player_ids by Team Boxscores.

**Comment by SpecCRA** [comment]
1. Got it. My pip doesn't seem to want to update from 1.0.7. There was my problem -_-

2&3. Understood. Thank you for the help!
