### ISSUE TITLE
https proxy not supported by Requests

### ISSUE THREAD

**Issue by Hermezilla** [swar/nba_api#77]
nba_api uses Requests that uses urllib3

I've been trying to use anything non-static from my work pc, but apparently there's not much one can do about it.

**Comment by swar** [comment]
Will the proxy work standalone with Requests?

I have it loading the proxy into `HTTP` and `HTTPS`: https://github.com/swar/nba_api/blob/master/nba_api/library/http.py#L92

**Comment by Hermezilla** [comment]
> Will the proxy work standalone with Requests?
No. The problem is with Requests. It's alright.
