### ISSUE TITLE
Player Posession statistics for individual games?

### ISSUE THREAD

**Issue by akaushik101** [swar/nba_api#78]
Hi Swar,

For a given game, I'd like summary statistics about how many of the posesssions ended with a given player, and if they ended with a shot made, a shot missed, or a turnover. Is the only way to do this to parse through the play by play data, or are there any alternative methods you know?

Thanks!

**Comment by swar** [comment]
Unfortunately, I am not aware of any alternative method off the top of my head. However, I have not put any research into this either so there may be another solution. The best way is to research the endpoints to see if it would work in your case.

PlayByPlay data will get you raw information that can be flexible to analyze for your use-case.

**Comment by chisox721** [comment]
Just to provide some context here, player/lineup possession counts could probably be done using PBP data from the NBA but they surprisingly make it way more difficult then it should by not including substitutions at the beginning of quarters (unless I'm missing something obvious).

**Comment by akaushik101** [comment]
Yeah that's what I ended up doing in the end -- using PBP data. I haven't yet found a workaround for the beginning of quarters problem, although I have a crude idea. I was wondering if anyone has any suggestions / thoughts.

**Comment by chisox721** [comment]
My first thought is that you could retroactively create the initial 5-man lineup for each quarter given the first 5 substitutions but that wouldn't track players that played the entire quarter. Under that circumstance I suppose you could create a list of unique player_ids and use that to find the 5th player?

**Comment by dafriedman97** [comment]
Here's some code to infer the starting players for every quarter. TL;DR it checks all players who do something (e.g. shoot, rebound, or get subbed out) and if they weren't subbed in earlier that quarter, they must have started.

This assumes you have a dataframe called `play_by_play` defined with `play_by_play = playbyplayv2.PlayByPlayV2(game_id).play_by_play.get_data_frame()` and two teams, `home` and `vis`. 
```
quarter_starters = {1: {home: set(), vis: set()}, 2: {home: set(), vis: set()}, 3: {home: set(), vis: set()}, 4: {home: set(), vis: set()}}
quarter_subs = {1: {home: set(), vis: set()}, 2: {home: set(), vis: set()}, 3: {home: set(), vis: set()}, 4: {home: set(), vis: set()}}
for row, vals in play_by_play.iterrows():
    if vals['EVENTMSGTYPE'] == 12: # new quarter—unknown lineup
        quarter = vals['PERIOD']
    if vals['EVENTMSGTYPE'] == 8: # substitution
        team = vals['PLAYER1_TEAM_ABBREVIATION'] 
        in_player, out_player = vals['PLAYER2_NAME'], vals['PLAYER1_NAME']
        quarter_subs[quarter][team].add(in_player)
        if out_player not in quarter_subs[quarter][team]: # wasn't subbed in this quarter -> must be a starter
            quarter_starters[quarter][team].add(out_player)
    else:
        for player_number in range(1, 4): # check all players to see if they were subbed in. If not, they were starters
            player, team = vals[f'PLAYER{player_number}_NAME'], vals[f'PLAYER{player_number}_TEAM_ABBREVIATION']
            if player is None or team is None:
                break
            elif player not in quarter_subs[quarter][team]: # wasn't subbed in this quarter -> must be a starter
                quarter_starters[quarter][team].add(player)
```
