### ISSUE TITLE
proxy useage

### ISSUE THREAD

**Issue by slizb** [swar/nba_api#81]
I've seen some discussion in other issues about proxy requests, but the usage of a proxy is not clear to me... Whats the preferred way to send a request through the api over a proxy? 

Say I have a proxy with address `12.34.567.89:1234`
Is there a way to send a request like 

```
from nba_api.stats.endpoints import videoevents

game_id = '0041800406'
event_id = '4'
event = videoevents.VideoEvents(game_id, event_id)
```

except from a proxy server? something like:
```
my_proxy = '12.34.567.89:1234'
event = videoevents.VideoEvents(game_id, event_id, proxy=my_proxy)
```

**Comment by swar** [comment]
> ```
> my_proxy = '12.34.567.89:1234'
> event = videoevents.VideoEvents(game_id, event_id, proxy=my_proxy)
> ```

That is exactly how you would go ahead and pass in a proxy.

I'm not sure about being able to pass in event_id without explicitly calling the argument name, but give it a try. It should work and populate it to the default order inside of the py file.
https://github.com/swar/nba_api/blob/master/nba_api/stats/endpoints/videoevents.py

**Comment by slizb** [comment]
Cool, thanks!  I just had to upgrade my installation.
