### ISSUE TITLE
playerprofilev2 career highs returning playoff career highs

### ISSUE THREAD

**Issue by processOverOutcome** [swar/nba_api#83]
First, thank you for developing and maintaining this api.

I noticed that the playerprofilev2 end point is returning playoff career high game stats (e.g., points) versus regular season career high game stats for each player.  I've tried numerous experiments and can't seem to find a way to source regular season career high game stats from nba.stats.com.  This is the webpage link for Lebron James (career highs are at the bottom) and match what is returned by playerprofilev2.

[https://stats.nba.com/player/2544/career/?PerMode=Totals](https://stats.nba.com/player/2544/career/?PerMode=Totals)

I am curious if you noticed this before and / or had any thoughts/suggestions.

Thank you.

**Comment by swar** [comment]
This is the endpoint url to access PlayerProfileV2: https://stats.nba.com/stats/playerprofilev2?LeagueID=00&PerMode=PerGame&PlayerID=2544

I don't think there is a way in here to filter strictly for Regular Season Career High Stats. This page only has Playoff highs. 

For example: https://stats.nba.com/player/202681/career/?PerMode=Totals

Kyrie's Career High in Assists is actually 18: https://basketball.realgm.com/player/Kyrie-Irving/Bests/7118

**Comment by swar** [comment]
I can't find another endpoint that would contain this information.

**Comment by processOverOutcome** [comment]
Thanks for the quick reply.  I'll let you know if I find an alternative solution.

**Comment by monsdar** [comment]
For anyone coming here from the search: CareerHighs and SeasonHighs are returned by the `PlayerCareerStats` endpoint, but only if you explicitly set the `league_id_nullable='00'` parameter.

Example:

```
# get stats for Kyrie
player_stats = playercareerstats.PlayerCareerStats(player_id=202681, per_mode36='PerGame', league_id_nullable='00').get_normalized_dict()

# get the 15th element of the CareerHighs, which as of 2025-04 is his assists
career_high_ast = player_stats['CareerHighs'][0][15]['STAT_VALUE']
```

The data is a bit strange to handle, as a player could have multiple games that tied his career high, therefore the returned list differs in size depending on the player.
