### ISSUE TITLE
leaguegamefinder.LeagueGameFinder() issues

### ISSUE THREAD

**Issue by pwu97** [swar/nba_api#86]
is anyone having a problem with this function? i'm getting:

TypeError: getresponse() got an unexpected keyword argument 'buffering'

and 

requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='stats.nba.com', port=443): Read timed out. (read timeout=30)

and 

a timeout error?

this is weird because it was working just a few days ago. might be a server issue on my part?

**Comment by swar** [comment]
It might be a server issue. Can you post the code you are trying to make?

**Comment by Pikus16** [comment]
I'm also having this issue. It's coming from the following line::
gamefinder = leaguegamefinder.LeagueGameFinder(team_id_nullable=celtics['id'])

**Comment by swar** [comment]
@Pikus16 

I have just tried that same line and I was able to have it go through using a team_id_nullable argument of `1`. What is your error traceback?

**Comment by BenikaH** [comment]
Having same issue with multiple calls.

**Comment by AlexisdlC** [comment]
Hi!

I'm having the same issue at the moment... It was working perfectly fine yesterday for me, has anyone any idea what might be happening and/or how to solve it?

Thanks

**Comment by swar** [comment]
@AlexisdlC 

Issue can be resolved temporarily here: #94

**Comment by swar** [comment]
Connection issues should be resolved as of [v1.1.5](https://github.com/swar/nba_api/releases/tag/v1.1.5).

This includes testing of this endpoint. It should be good to go. If not, please reopen the issue or create another one.
