### ISSUE TITLE
Shot Chart Detail Issue

### ISSUE THREAD

**Issue by janjuana1** [swar/nba_api#87]
The endpoint is working but the only issue I have is I am only receiving data for shots made. I would like to have access to shots missed as well. Would I have to specify that somewhere in the pull request? Thanks! Very much appreciate all the work you've done!

**Comment by swar** [comment]
You can change the context measure to `FGA` instead. 

https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/shotchartdetail.md

**Comment by janjuana1** [comment]
Thank you!
