### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by janjuana1** [swar/nba_api#88]
I was able to access the api until two days ago. I keep receiving this error when trying to retrieve information. Any suggestions? 

ConnectionError: ('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))

Thanks!

**Comment by swar** [comment]
What country are you located in? it might be a headers issue. Can you access NBA Stats via browser?

**Comment by janjuana1** [comment]
I am in the United States and can access it via browser. I was able to pull information previously but it stopped all of a sudden.

**Comment by swar** [comment]
This might be in relation to the library automatically changing over to the next season when October hits. If you hardcore your season argument to 2018-19, does it start working?

**Comment by janjuana1** [comment]
Still not working. Might be do to my IP? I tried it on another network and it work.

**Comment by swar** [comment]
I think that's a fair assumption to make. Although, if it works in browser, it should work through Python.

**Comment by janjuana1** [comment]
Hmm yea not sure why it’s doing this. Do you have any recommendations other than connecting to a different internet connection?

**Comment by swar** [comment]
My only other recommendation is to update your headers and try that. That is my best guess on what's causing it to fail.

**Comment by janjuana1** [comment]
Ok so I tried it on a different computer on the same network and am receiving this error on that computer. 
"ConnectionError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))"

Have you seen this one before?

Appreciate the help too!

**Comment by keyic** [comment]
Same problem...

**Comment by swar** [comment]
I need more information from both of you to determine what's happening. Please post the entire traceback as well as the code that you are trying to enter.


The short error saying `An existing connection was forcibly closed by the remote host` can mean that you're entering malformed data to an argument(s), the server is rejecting your connection, or a wide range of other issues.

**Comment by keyic** [comment]
@swar
Here is my code.
 `from nba_api.stats.endpoints import commonplayerinfo
player_info = commonplayerinfo.CommonPlayerInfo(player_id=203991)`

And I got error as "('Connection aborted.', OSError("(10054, 'WSAECONNRESET')"))" 

I am in the United States and I can also open the URL: https://stats.nba.com/stats/commonplayerinfo?LeagueID=&PlayerID=203991

**Comment by swar** [comment]
@keyic What country are you in?

I am able to get that working on my end. Do you know how to get the headers from your browser? I think you are experiencing a headers issue if you are out of the country. Please try passing custom headers in and see if that works.

```Python
headers = {} # GET HEADERS
player_info = commonplayerinfo.CommonPlayerInfo(player_id=203991, headers=headers)
```

**Comment by keyic** [comment]
@swar Hi, I am in the country. But I think whenever I directly sent a request to the API URL it will return that kind of error. Also if too many requests by your library, there will be a kind of "excessive requests" error. Avoid direct scrapping the URL and using sleep() for many API requests solved my problem.

Thanks!
