### ISSUE TITLE
Updating static players list

### ISSUE THREAD

**Issue by dhurd55** [swar/nba_api#91]
How can I update the list with rookies names and ids?

**Comment by swar** [comment]
If you have the repo downloaded, you can run the static file script located here:

https://github.com/swar/nba_api/blob/master/scripts/create_static_data_file.py

I need to re-run this for this year, but I am having a computer issue that's causing delays.

**Comment by swar** [comment]
Updated static player list as of [v1.1.5](https://github.com/swar/nba_api/releases/tag/v1.1.5)
