### ISSUE TITLE
Game stats don't update nearly in realtime?

### ISSUE THREAD

**Issue by ntsirakis** [swar/nba_api#93]
Seems like the game stats are way behind the realtime totals; I fetched the game between the Rockets and Grizzlies last night and the API reported that it was still halftime when the game was 9 minutes into the 3rd quarter. Looks like an issue on nba.com's end; do you know if this has always been the case? Is there a reliable way to contact them?

**Comment by swar** [comment]
Unfortunately, I can't help with this question. I'll leave it up incase anyone else has any insight.
