### ISSUE TITLE
LeagueGameFinder returns an empty data array

### ISSUE THREAD

**Issue by maxjaksa** [swar/nba_api#95]
Hi swar, thanks so much for creating this api! I am loving it.

So prior to the changes that occurred on stats.nba.com that forced your recent header changes (see: https://github.com/swar/nba_api/issues/94), I was using the LeagueGameFinder to pull down various bits of game data.  When that change occurred I got the connection issue reported above.  

After adding headers, I no longer get the connection issue, but the object returned from `LeagueGameFinder` doesn’t return any meaningful results (the `league_game_finder_results.data` array always comes up empty, regardless of the query/params).  Any idea what might be causing this?

Sample `LeagueGameFinder` api call from my application (just in case I'm doing something terribly wrong):

`raw_game_data = leaguegamefinder.LeagueGameFinder(date_from_nullable=start, date_to_nullable=end, league_id_nullable=LeagueIDNullable().nba, season_type_nullable=SeasonType().regular)`

**Comment by swar** [comment]
What are you passing to start and end?

I just ran what you sent here without start and `date_from_nullable` and `date_to_nullable` and I was able to receive data.

```python
from nba_api.stats.library.parameters import *
from nba_api.stats.endpoints import *

raw_game_data = leaguegamefinder.LeagueGameFinder(league_id_nullable=LeagueIDNullable().nba, season_type_nullable=SeasonType().regular)
```

**Comment by maxjaksa** [comment]
Hi @swar, I'm just passing in strings formatted like so:  "m/d/yyyy"

Example: `start='10/6/2019', end'10/7/2019'`

After some initial trial and error it seemed that this was the date format that `LeagueGameFinder` was expecting.  This was all working fine earlier this past week.

**Comment by swar** [comment]
Could the issue be that there were no regular season games played 2019-10-06 and 2019-10-07?

I get results when I switch `season_type_nullable` to `SeasonType().preseason` instead.

**Comment by swar** [comment]
Also if this is still an issue, if you switch back to `v1.1.4` does it still work?

**Comment by swar** [comment]
Feel free to reopen if you're still having this issue.
