### ISSUE TITLE
Look into why Atlanta is the state for the Atlanta Hawks

### ISSUE THREAD

**Issue by swar** [swar/nba_api#96]
I believe this is because the backend was showing Atlanta as the state. 

Found here: https://github.com/swar/nba_api/blob/master/nba_api/stats/library/data.py#L4510

**Comment by dfelsie** [comment]
I think this issue can be closed, since the backend now properly shows Georgia as the state
(https://github.com/swar/nba_api/blob/master/src/nba_api/stats/library/data.py#L4838)
and the file with the error no longer exists.
