### ISSUE TITLE
Pull upcoming schedule matchup data

### ISSUE THREAD

**Issue by romanbogza** [swar/nba_api#97]
Hi Swar,

Thanks for this code. This helps me with my fantasy project.
I don't see a way to pull NBA upcoming schedules easily. I want to know all matchups for a  given day (or day range). Is there an endpoint for that?

**Comment by swar** [comment]
I think you will have luck with this endpoint: https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/scoreboardv2.md

**Comment by romanbogza** [comment]
is it just me or are these APIs really slow and very inconcsitent?

**Comment by swar** [comment]
I don't find an issue with them being relatively slow, but you could be getting throttled. What do you mean by inconsistent?

**Comment by swar** [comment]
Feel free to reopen or create a new ticket if you still have questions.
